# Generated by Django 6.1.1 on 2026-10-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_whatsapp_number'),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='managed_departments',
            field=models.ManyToManyField(blank=True, related_name='authorized_managers', to='institutions.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='management_scope',
            field=models.CharField(blank=True, choices=[('HOD', 'Head of Department'), ('DEAN', 'Dean')], default='', max_length=10),
        ),
    ]
