# Generated by Django 6.1.1 on 2026-09-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_alter_faculty_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
