# Generated by Django 6.1.1 on 2026-09-24 17:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_faculty_name'),
        ('scheduling', '0003_timetableversion_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyArrangement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arrangement_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ASSIGNED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('absent_faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='absence_arrangements', to='faculty.faculty')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_faculty_arrangements', to=settings.AUTH_USER_MODEL)),
                ('schedule_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrangements', to='scheduling.scheduleentry')),
                ('substitute_faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substitute_arrangements', to='faculty.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='ArrangementAttendanceEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='private/arrangement-evidence/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField()),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_arrangement_evidence', to=settings.AUTH_USER_MODEL)),
                ('arrangement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='faculty.facultyarrangement')),
            ],
        ),
        migrations.AddIndex(
            model_name='facultyarrangement',
            index=models.Index(fields=['arrangement_date', 'status'], name='faculty_fac_arrange_f94c53_idx'),
        ),
        migrations.AddIndex(
            model_name='facultyarrangement',
            index=models.Index(fields=['absent_faculty', 'arrangement_date'], name='faculty_fac_absent__ad8cb6_idx'),
        ),
        migrations.AddIndex(
            model_name='facultyarrangement',
            index=models.Index(fields=['substitute_faculty', 'arrangement_date'], name='faculty_fac_substit_f93287_idx'),
        ),
        migrations.AddConstraint(
            model_name='facultyarrangement',
            constraint=models.UniqueConstraint(fields=('schedule_entry', 'arrangement_date'), name='unique_arrangement_entry_date'),
        ),
    ]
