# Generated by Django 6.1.1 on 2026-09-20 21:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('building', models.CharField(max_length=100)),
                ('floor', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField()),
                ('room_type', models.CharField(choices=[('CLASSROOM', 'Classroom'), ('COMPUTER_LAB', 'Computer Lab'), ('LAB', 'Lab'), ('SEMINAR_HALL', 'Seminar Hall'), ('AUDITORIUM', 'Auditorium'), ('OTHER', 'Other')], default='CLASSROOM', max_length=50)),
                ('facilities', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.IntegerField(blank=True, help_text='0 for Monday, 6 for Sunday', null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BLOCKED', 'Blocked'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='rooms.room')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.timeslot')),
            ],
        ),
    ]
