# Generated by Django 6.1.1 on 2026-10-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_allowed_year_first_year_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('CLASSROOM', 'Classroom'), ('COMPUTER_LAB', 'Computer Lab'), ('LAB', 'Lab'), ('SEMINAR_HALL', 'Seminar Hall'), ('AUDITORIUM', 'Auditorium'), ('ELECTRICAL LAB', 'Electrical Lab'), ('WORKSHOP', 'Workshop'), ('MECHANICS LAB', 'Mechanics Lab'), ('ENGINEERING GRAPHICS LAB', 'Engineering Graphics Lab'), ('PHYSICS LAB', 'Physics Lab'), ('SUSTAINABLE CHEMICAL SCIENCES LAB', 'Sustainable Chemical Sciences Lab'), ('OTHER', 'Other')], default='CLASSROOM', max_length=50),
        ),
    ]
