# Generated by Django 6.1.1 on 2026-10-07 15:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_courseoffering_allow_remainder_period'),
        ('institutions', '0001_initial'),
        ('rooms', '0006_canonical_room_types_and_lgf_master_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomEligibilityException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField()),
                ('allow', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_eligibility_exceptions', to='academics.course')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_eligibility_exceptions', to='institutions.program')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_exceptions', to='rooms.room')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('room', 'program', 'year', 'course'), name='unique_room_eligibility_exception_scope')],
            },
        ),
    ]
