# Generated by Django 6.1.1 on 2026-10-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_ncs4353_year2_room_exception'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(
                choices=[
                    ('CLASSROOM', 'Classroom'),
                    ('COMPUTER_LAB', 'Computer Lab'),
                    ('LAB', 'Lab'),
                    ('SEMINAR_HALL', 'Seminar Hall'),
                    ('AUDITORIUM', 'Auditorium'),
                    ('ELECTRICAL_LAB', 'Electrical Lab'),
                    ('WORKSHOP', 'Workshop'),
                    ('MECHANICS_LAB', 'Mechanics Lab'),
                    ('ENGINEERING_GRAPHICS_LAB', 'Engineering Graphics Lab'),
                    ('PHYSICS_LAB', 'Physics Lab'),
                    ('SUSTAINABLE_CHEMICAL_SCIENCES_LAB', 'Sustainable Chemical Sciences Lab'),
                    ('QUANTUM_PHYSICS_ADVANCED_FUNCTIONAL_MATERIALS_LAB', 'Quantum Physics and Advanced Functional Materials Lab'),
                    ('OTHER', 'Other'),
                ],
                default='CLASSROOM',
                max_length=50,
            ),
        ),
    ]
