/* eslint-disable @typescript-eslint/no-explicit-any */
import { apiClient } from './client';
export type Timetable = { id:string; title:string; academic_session:string; semester:string; department:string; effective_date?:string; active?:boolean; updated_at:string };
export type Version = { id:string; timetable:string; version_no:number; status:string; entry_count:number; created_by?:string; created_at:string; notes?:string };
export type TimeSlot = { id:string; name?:string; label?:string; start_time:string; end_time:string; is_break?:boolean; slot_type?:string };
export type ScheduleEntry = { id:string; version:string; section:string; section_name?:string; course_offering:string; course?:{id:string;code:string;name:string;short_code?:string}; weekday:number; start_slot:string; block_length:number; room?:string; room_code?:string; entry_type:string; locked:boolean; faculty_ids?:string[] };
export type Conflict = { code?:string; type?:string; message:string; metadata?:Record<string,unknown> };
export type ValidationResult = { valid:boolean; conflicts:Conflict[]; warnings?:Conflict[]; course_completion?:{course_offering:string;course?:string;required:number;scheduled:number;remaining:number;complete:boolean}[] };
export type ListResponse<T> = T[] | { results:T[]; count?:number };
const unwrap = <T,>(data:ListResponse<T>|{entries?:T[]}) => Array.isArray(data) ? data : ('results' in data ? data.results ?? [] : data.entries ?? []);
const list = async <T,>(url:string, params?:Record<string,unknown>) => unwrap<T>((await apiClient.get<ListResponse<T>>(url,{params})).data);
export const schedulingApi = { list:()=>list<Timetable>('/timetables/'), detail:async(id:string)=>(await apiClient.get<Timetable>(`/timetables/${id}/`)).data, create:async(payload:Record<string,unknown>)=>(await apiClient.post<Timetable>('/timetables/',payload)).data, listVersions:(id:string)=>list<Version>(`/timetables/${id}/versions/`), cloneVersion:async(id:string,notes='')=>(await apiClient.post<Version>(`/timetables/${id}/versions/`,{clone_from:id,notes})).data, entries:(id:string,params?:Record<string,unknown>)=>list<ScheduleEntry>(`/versions/${id}/entries/`,params), createEntry:async(id:string,payload:Record<string,unknown>)=>(await apiClient.post<ScheduleEntry>(`/versions/${id}/entries/`,payload)).data, updateEntry:async(version:string,entry:string,payload:Record<string,unknown>)=>(await apiClient.patch<ScheduleEntry>(`/versions/${version}/entries/${entry}/`,payload)).data, deleteEntry:async(version:string,entry:string)=>{await apiClient.delete(`/versions/${version}/entries/${entry}/`);}, lockEntry:async(entry:string)=>(await apiClient.post(`/entries/${entry}/lock/`)).data, unlockEntry:async(entry:string)=>(await apiClient.post(`/entries/${entry}/unlock/`)).data, validateEntry:async(id:string,payload:Record<string,unknown>)=>(await apiClient.post<ValidationResult>(`/versions/${id}/validate-entry/`,payload)).data, validate:async(id:string)=>(await apiClient.post<ValidationResult>(`/versions/${id}/validate/`)).data, sectionTimetable:(id:string,section?:string)=>list<ScheduleEntry>(`/versions/${id}/section-timetable/`,section?{section}:undefined), facultyTimetable:(id:string,faculty?:string)=>list<ScheduleEntry>(`/versions/${id}/faculty-timetable/`,faculty?{faculty}:undefined), roomAllocation:(id:string,params?:Record<string,unknown>)=>list<ScheduleEntry>(`/versions/${id}/room-allocation/`,params), availableRooms:(id:string,params:Record<string,unknown>)=>list<any>(`/versions/${id}/available-rooms/`,params) };
