'use client';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { apiErrorMessage, downloadFacultyAvailabilityTemplate, downloadRoomImportTemplate, downloadTimeSlotTemplate, uploadImport } from '@/lib/api/resources';
import { CourseOfferingImportDialog } from '@/components/CourseOfferingImportDialog';

type Result = { total?: number; total_rows?: number; create?: number; update?: number; archive?: number; invalid?: number; invalid_rows?: number; errors?: { row: number; identifier?: string; message: string }[] };
export function BulkImportDialog({ kind, onComplete, buttonLabel }: { kind: string; onComplete: () => void; buttonLabel?: string }) {
  const [file, setFile] = useState<File | null>(null), [preview, setPreview] = useState<Result | null>(null), [open, setOpen] = useState(false), [busy, setBusy] = useState(false), [mode, setMode] = useState('UPSERT'), [error, setError] = useState('');
  if (kind === 'course-offerings') return <CourseOfferingImportDialog onComplete={onComplete} />;
  const close = () => { setOpen(false); setFile(null); setPreview(null); setError(''); };
  const run = async (action: 'preview' | 'commit') => { if (!file) return; setBusy(true); setError(''); try { const data = await uploadImport(kind, action, file, (kind === 'courses' || kind === 'faculty') ? { import_mode: mode } : undefined) as Result; if (action === 'preview') setPreview(data); else { close(); onComplete(); } } catch (requestError: unknown) { setError(apiErrorMessage(requestError, `Could not ${action === 'preview' ? 'preview' : 'import'} ${kind}.`)); } finally { setBusy(false); } };
  return <><Button variant="outline" onClick={() => { setError(''); setOpen(true); }}>{buttonLabel ?? 'Import'}</Button>{open && <div className="fixed inset-0 z-30 flex items-center justify-center bg-black/30 p-4"><div className="w-full max-w-2xl rounded-xl bg-white p-6"><h2 className="text-lg font-semibold">Import {kind}</h2>{error && <p className="mt-3 rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}{(kind === 'courses' || kind === 'faculty') && <label className="mt-4 block text-sm">Import mode<select className="mt-1 block rounded border p-2" value={mode} onChange={(e) => setMode(e.target.value)}><option value="UPSERT">Update existing &amp; add new</option><option value="CREATE_ONLY">Add new only</option><option value="REPLACE">Replace active list</option></select></label>}{kind === 'time-slots' && <Button variant="outline" className="mt-4" onClick={() => void downloadTimeSlotTemplate()}>Download Template</Button>}<input className="my-4 block w-full" type="file" accept=".csv,.xlsx" onChange={(e) => { setFile(e.target.files?.[0] ?? null); setPreview(null); setError(''); }} />{kind === 'rooms' && <Button variant="outline" onClick={() => void downloadRoomImportTemplate()}>Download Template</Button>}{kind === 'faculty-availability' && <Button variant="outline" onClick={() => void downloadFacultyAvailabilityTemplate()}>Download Template</Button>}<div className="mt-4 flex gap-2"><Button disabled={!file || busy} onClick={() => void run('preview')}>{busy ? 'Working...' : 'Preview'}</Button><Button disabled={!preview || !!(preview.invalid ?? preview.invalid_rows) || busy} onClick={() => void run('commit')}>Import</Button><Button variant="outline" onClick={close}>Cancel</Button></div>{preview && <div className="mt-4 text-sm"><p>Total: {preview.total ?? preview.total_rows ?? 0} · Create: {preview.create ?? 0} · Update: {preview.update ?? 0} · Invalid: {preview.invalid ?? preview.invalid_rows ?? 0}</p>{(preview.errors ?? []).map((item) => <p className="text-red-600" key={`${item.row}-${item.message}`}>Row {item.row} — {item.identifier ?? ''}: {item.message}</p>)}</div>}</div></div>}</>;
}
