/* eslint-disable @typescript-eslint/no-explicit-any */
'use client';
import { Button } from '@/components/ui/button';
import { Card,CardContent,CardHeader,CardTitle } from '@/components/ui/card';
import { apiClient } from '@/lib/api/client';
import { Conflict,ScheduleEntry,TimeSlot } from '@/lib/api/scheduling';
export const conflictLabel=(c:string)=>c.replaceAll('_',' ').toLowerCase().replace(/(^| )\w/g,x=>x.toUpperCase());
export function ConflictList({items=[]}:{items:Conflict[]}){return <div className="space-y-2">{items.map((c,i)=><div key={i} className="rounded border border-red-200 bg-red-50 p-3"><div className="font-medium text-red-900">{conflictLabel(c.code||c.type||'Conflict')}</div><div className="text-sm text-red-800">{c.message}</div></div>)}</div>}
export function TimetableGrid({slots,entries,onCellClick,onEntryClick,readOnly=false}:{slots:TimeSlot[];entries:ScheduleEntry[];onCellClick?:(day:number,slot:TimeSlot)=>void;onEntryClick?:(entry:ScheduleEntry)=>void;readOnly?:boolean}){const days=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];return <div className="overflow-x-auto"><table className="min-w-[900px] w-full border-collapse text-sm"><thead><tr><th className="sticky left-0 bg-white p-3 text-left">Day</th>{slots.map(s=><th key={s.id} className="border p-2 text-center">{s.label||s.name||`${s.start_time}–${s.end_time}`}</th>)}</tr></thead><tbody>{days.map((day,d)=><tr key={day}><th className="sticky left-0 bg-white p-3 text-left">{day}</th>{slots.map(slot=>{const e=entries.find(x=>x.weekday===d&&x.start_slot===slot.id);return <td key={slot.id} className={`h-24 min-w-32 border p-1 align-top ${slot.is_break?'bg-amber-50':'bg-slate-50'}`}>{slot.is_break?<div className="p-2 text-center text-xs font-semibold text-amber-700">BREAK</div>:e?<button disabled={readOnly&& !onEntryClick} onClick={()=>onEntryClick?.(e)} className="h-full w-full rounded bg-blue-100 p-2 text-left hover:bg-blue-200"><div className="text-[10px] font-semibold uppercase">{e.entry_type}</div><div className="font-medium">{e.course?.code||'Course'}</div><div className="text-xs">{e.course?.name||''}</div><div className="text-xs">{e.room_code||'Room pending'}</div>{e.block_length>1&&<span className="text-[10px]">{e.block_length} periods</span>}{e.locked&&<span className="ml-1 text-[10px]">🔒</span>}</button>:<button disabled={readOnly} onClick={()=>onCellClick?.(d,slot)} className="h-full w-full rounded border border-dashed border-slate-200 text-slate-400 hover:bg-white">+</button>}</td>})}</tr>)}</tbody></table></div>}
export function ValidationPanel({result,onClose}:{result:{valid:boolean;conflicts:Conflict[];warnings?:Conflict[];course_completion?:{course_offering:string;course?:string;required:number;scheduled:number;remaining:number;complete:boolean}[]};onClose:()=>void}){return <Card className="mt-4"><CardHeader><CardTitle className={result.valid?'text-emerald-700':'text-red-700'}>{result.valid?'Valid timetable':'Timetable has conflicts'}</CardTitle></CardHeader><CardContent><p className="mb-3 text-sm">{result.conflicts.length} blocking conflict(s), {(result.warnings||[]).length} warning(s)</p><ConflictList items={result.conflicts}/>{result.course_completion&&<div className="mt-4"><h3 className="mb-2 font-medium">Course completion</h3>{result.course_completion.map((c,i)=><div key={i} className="mb-2 flex justify-between rounded bg-slate-50 p-2 text-sm"><span>{c.course||c.course_offering}</span><span>{c.scheduled}/{c.required} {c.complete?'Complete':`${c.remaining} remaining`}</span></div>)}</div>}<Button className="mt-3" variant="outline" onClick={onClose}>Close</Button></CardContent></Card>}
const optionCache=new Map<string,Promise<any[]>>();
export function fetchOptions(path:string):Promise<any[]>{const cached=optionCache.get(path);if(cached)return cached;const request=(async()=>{const items:any[]=[];let next:string|null=path;while(next){const result:{data:any[]|{results?:any[];next?:string|null}}=await apiClient.get<any[]|{results?:any[];next?:string|null}>(next);const data:any[]=Array.isArray(result.data)?result.data:result.data.results||[];items.push(...data);next=Array.isArray(result.data)?null:result.data.next||null}return items})();optionCache.set(path,request);return request;}
