# Generated by Django 6.1.1 on 2026-09-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lecture_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='practical_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='tutorial_hours',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
