# Generated by Django 6.1.1 on 2026-09-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_course_lecture_hours_course_practical_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
