# Generated by Django 6.1.1 on 2026-10-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_courseoffering_allow_remainder_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='coordinator_mobile',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='section',
            name='coordinator_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
