# Generated by Django 6.1.1 on 2026-10-08 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_section_timetable_scope_and_coordinator'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionDeliveryPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('STANDARD', 'Standard (physical room required)'), ('HYBRID', 'Hybrid (one offline weekday)')], default='HYBRID', max_length=12)),
                ('offline_weekday', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday')], null=True)),
                ('source', models.CharField(choices=[('OFFICIAL_TIMETABLE', 'Official timetable'), ('ADMIN', 'Administrator')], default='OFFICIAL_TIMETABLE', max_length=24)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_delivery_policies', to='academics.academicsession')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_delivery_policies', to='academics.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_delivery_policies', to='academics.semester')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('section', 'academic_session', 'semester'), name='unique_section_period_delivery_policy')],
            },
        ),
    ]
