# Generated by Django 6.1.1 on 2026-10-08 07:07

import django.db.models.deletion
from django.db import migrations, models


OFFICIAL_OFF_DAYS = {
    2: {
        'CS-2B': 3, 'CS-2C': 2, 'CS-2D': 4, 'CS-2E': 0, 'CS-2F': 3,
        'CSAI-2A': 2, 'CSAI-2B': 1, 'CSAI-2C': 4, 'CSAI-2D': 3,
        'CSAI-2E': 2, 'CSAI-2F': 0, 'CSAI-2G': 4, 'CCML-2A': 1,
        'AIBC-2A': 3,
    },
    3: {
        'CS-3A': 0, 'CS-3B': 1, 'CS-3C': 2, 'CS-3D': 4,
        'CS-3E': 0, 'CS-3F': 1, 'CS-3G': 2, 'CS-3H': 3,
        'CSE(AI)-3A': 0, 'CSE(AI)-3B': 1, 'CSE(AI)-3C': 4,
        'CSE(AI)-3D': 0, 'CSE(AI)-3E': 1, 'CSE(AI)-3F': 3,
        'CSE(AI)-3G': 0, 'CSE(AI)-3H': 1, 'CSE(CCML)-3A': 0,
        'CSE(IOTBC)-3A': 4,
    },
}


def seed_official_weekly_off_days(apps, schema_editor):
    Session = apps.get_model('academics', 'AcademicSession')
    Semester = apps.get_model('academics', 'Semester')
    Section = apps.get_model('academics', 'Section')
    CourseOffering = apps.get_model('academics', 'CourseOffering')
    Policy = apps.get_model('academics', 'SectionWeeklyOffPolicy')
    session = Session.objects.filter(name='2026-27', institution__departments__programs__code='BTECH-CSE').distinct().first()
    if session is None:
        return
    semesters = list(Semester.objects.filter(session=session, type='ODD'))
    if len(semesters) != 1:
        if not semesters:
            return
        raise RuntimeError('Expected a single Odd Semester for 2026-27 when seeding official weekly OFF-day policies.')
    semester = semesters[0]
    program_ids = list(apps.get_model('institutions', 'Program').objects.filter(
        department__institution=session.institution, code='BTECH-CSE').values_list('id', flat=True))
    for year, section_days in OFFICIAL_OFF_DAYS.items():
        for name, weekday in section_days.items():
            matches = list(Section.objects.filter(program_id__in=program_ids, semester=semester, year=year, name=name))
            if len(matches) > 1:
                raise RuntimeError(f'Multiple BTECH-CSE Year {year} sections named {name} exist in 2026-27 Odd Semester; refusing ambiguous weekly OFF-day seed.')
            if not matches or not CourseOffering.objects.filter(section=matches[0], active=True).exists():
                continue
            section = matches[0]
            existing = Policy.objects.filter(section=section, academic_session=session, semester=semester, is_active=True).first()
            if existing:
                if existing.weekday != weekday:
                    raise RuntimeError(f'Conflicting active weekly OFF-day policy already exists for {section.name}; refusing to overwrite it.')
                continue
            Policy.objects.create(section=section, academic_session=session, semester=semester,
                                  weekday=weekday, source='OFFICIAL_TIMETABLE', is_active=True)


def unseed_official_weekly_off_days(apps, schema_editor):
    # Keep policy data on rollback; migration reversal must not erase admin edits.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_official_btech_cse_year4_hybrid'),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionWeeklyOffPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday')])),
                ('source', models.CharField(choices=[('OFFICIAL_TIMETABLE', 'Official timetable'), ('ADMIN', 'Administrator')], default='OFFICIAL_TIMETABLE', max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_weekly_off_policies', to='academics.academicsession')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_off_policies', to='academics.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_weekly_off_policies', to='academics.semester')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('section', 'academic_session', 'semester'), name='unique_active_section_weekly_off')],
            },
        ),
        migrations.RunPython(seed_official_weekly_off_days, unseed_official_weekly_off_days),
    ]
