# Generated by Django 6.1.1 on 2026-10-08 08:09

from django.db import migrations, models


CS2A_SECTION_ID = '77397aae-b7de-44fc-963c-ca8c1e58484b'


def seed_cs2a_no_weekly_off(apps, schema_editor):
    Section = apps.get_model('academics', 'Section')
    Policy = apps.get_model('academics', 'SectionWeeklyOffPolicy')
    section = Section.objects.filter(
        pk=CS2A_SECTION_ID,
        name='CS-2A',
        year=2,
        program__code='BTECH-CSE',
        semester__session__name='2026-27',
        semester__type='ODD',
    ).first()
    if section is None:
        # Empty/test installations may not contain institutional source data.
        # Seed only when the exact authoritative section exists.
        return
    active = Policy.objects.filter(section=section, academic_session=section.semester.session,
                                   semester=section.semester, is_active=True).first()
    if active:
        if active.policy_type != 'NO_WEEKLY_OFF' or active.weekday is not None:
            raise RuntimeError('CS-2A already has a conflicting active weekly OFF policy; refusing to overwrite it.')
        return
    Policy.objects.create(
        section=section,
        academic_session=section.semester.session,
        semester=section.semester,
        policy_type='NO_WEEKLY_OFF',
        weekday=None,
        source='OFFICIAL_TIMETABLE',
        is_active=True,
    )


def preserve_policy_on_reverse(apps, schema_editor):
    # Never erase this authoritative source record when rolling back schema.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_sectionweeklyoffpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionweeklyoffpolicy',
            name='policy_type',
            field=models.CharField(choices=[('WEEKLY_OFF', 'Weekly OFF day'), ('NO_WEEKLY_OFF', 'No weekly OFF day')], default='WEEKLY_OFF', max_length=20),
        ),
        migrations.AlterField(
            model_name='sectionweeklyoffpolicy',
            name='weekday',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday')], null=True),
        ),
        migrations.AddConstraint(
            model_name='sectionweeklyoffpolicy',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('policy_type', 'WEEKLY_OFF'), ('weekday__isnull', False)), models.Q(('policy_type', 'NO_WEEKLY_OFF'), ('weekday__isnull', True)), _connector='OR'), name='weekly_off_type_matches_weekday'),
        ),
        migrations.RunPython(seed_cs2a_no_weekly_off, preserve_policy_on_reverse),
    ]
