'use client';
import {useMemo,useState} from 'react';
import {Card,CardContent,CardHeader,CardTitle} from '@/components/ui/card';
import {Button} from '@/components/ui/button';
import {GeneratedEntry,GenerationRun,TimeSlot} from '@/lib/api/scheduling';
type Person={id:string;name?:string;initials?:string;employee_code?:string};
type Section={id:string;name?:string;label?:string;program_name?:string;semester_name?:string};
const days=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
const human=(x?:string)=>x?.replaceAll('_',' ').toLowerCase().replace(/(^| )\w/g,c=>c.toUpperCase())??'Unknown';
const personName=(p?:Person)=>p?.name??[p?.initials,p?.employee_code].filter(Boolean).join(' · ')??'Faculty unavailable';
export function GenerationPreview({run,slots,faculty,sections,onApply,applied}:{run:GenerationRun;slots:TimeSlot[];faculty:Person[];sections:Section[];onApply:()=>void;applied:string}){
 const entries=run.result?.entries??[];const ids=[...new Set(entries.map(x=>x.section_id).filter((x):x is string=>!!x))];const available=ids.length?ids:sections.map(x=>x.id);const [active,setActive]=useState(available[0]??'');
 const people=useMemo(()=>new Map(faculty.map(x=>[x.id,x])),[faculty]);const visible=entries.filter(x=>!active||x.section_id===active);const byCell=new Map(visible.map(x=>[`${x.weekday}:${x.start_slot_id}`,x]));const covered=new Set<string>();
 const facultyText=(e:GeneratedEntry)=>e.faculty_assignments?.map(a=>`${personName(people.get(a.faculty_id))} — ${human(a.role)}`).join(', ')||'Faculty unavailable';
 return <Card><CardHeader><CardTitle>Generated timetable preview</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 sm:grid-cols-4"><p><b>Solver</b><br/>{human(run.solver_status)}</p><p><b>Objective</b><br/>{run.objective_score??'—'}</p><p><b>Generated entries</b><br/>{visible.length}</p><p><b>Solve time</b><br/>{run.statistics?.solve_time_seconds??'—'} seconds</p></div>{available.length>1&&<label className="block text-sm font-medium">Preview section<select className="ml-2 rounded border p-2" value={active} onChange={e=>setActive(e.target.value)}>{available.map(x=>{const s=sections.find(y=>y.id===x);return <option key={x} value={x}>{s?[s.program_name,s.semester_name,s.name??s.label].filter(Boolean).join(' — '):'Section unavailable'}</option>})}</select></label>}{!visible.length?<p className="rounded bg-slate-50 p-3 text-sm text-slate-600">No preview entries are available for this section.</p>:<div className="overflow-x-auto"><table className="min-w-[900px] w-full border-collapse text-sm"><thead><tr><th className="border p-2">Time slot</th>{days.map(x=><th className="border p-2" key={x}>{x}</th>)}</tr></thead><tbody>{slots.map((slot,i)=><tr key={slot.id}><th className={`border p-2 text-left ${slot.is_break?'bg-amber-50':''}`}>{slot.label??slot.start_time}{slot.is_break?' · BREAK':''}</th>{days.map((_,day)=>{const key=`${day}:${slot.id}`;if(covered.has(key))return null;const e=byCell.get(key);if(!e||slot.is_break)return <td className="h-20 min-w-36 border p-1 align-top" key={day}/>;const start=i;let span=1;for(let n=1;n<e.block_length&&start+n<slots.length;n++){if(slots[start+n].is_break)break;covered.add(`${day}:${slots[start+n].id}`);span++}return <td className="min-w-36 border p-1 align-top" key={day} rowSpan={span}><div className={`rounded p-2 ${e.state==='FIXED'?'bg-slate-200':e.state==='PRESERVED'?'bg-emerald-100':'bg-blue-100'}`}><b>{human(e.state??'GENERATED')}</b><div>{e.course_offering??'Course'}</div><div>{e.entry_type??'LECTURE'} · {e.block_length} period(s)</div><div className="text-xs">Room {e.room_id??'pending'}</div><div className="text-xs">{facultyText(e)}</div></div></td>})}</tr>)}</tbody></table></div>}{applied||run.applied_version?<p className="rounded bg-green-50 p-3 text-green-700">Applied to version {applied||run.applied_version}</p>:<Button disabled={!['OPTIMAL','FEASIBLE'].includes(run.solver_status??'')} onClick={onApply}>Apply as New Draft Version</Button>}</CardContent></Card>;
}
