# Generated by Django 6.1.1 on 2026-09-21 00:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(default='FILL_GAPS', max_length=40)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('INFEASIBLE', 'Infeasible'), ('FAILED', 'Failed'), ('APPLIED', 'Applied')], default='PENDING', max_length=20)),
                ('solver_status', models.CharField(blank=True, choices=[('OPTIMAL', 'Optimal'), ('FEASIBLE', 'Feasible'), ('INFEASIBLE', 'Infeasible'), ('MODEL_INVALID', 'Model Invalid'), ('UNKNOWN', 'Unknown')], max_length=20)),
                ('input_config', models.JSONField(default=dict)),
                ('input_snapshot', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('diagnostics', models.JSONField(default=dict)),
                ('statistics', models.JSONField(default=dict)),
                ('objective_score', models.FloatField(blank=True, null=True)),
                ('source_fingerprint', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('applied_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applied_generation_runs', to='scheduling.timetableversion')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generation_runs', to=settings.AUTH_USER_MODEL)),
                ('source_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generation_runs', to='scheduling.timetableversion')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_runs', to='scheduling.timetable')),
            ],
        ),
    ]
