# Generated by Django 6.1.1 on 2026-09-21 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_generationrun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableversion',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetableversion',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_timetable_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetableversion',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetableversion',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_timetable_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetableversion',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='timetableversion',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetableversion',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_timetable_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timetableversion',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived'), ('PENDING_APPROVAL', 'Pending Approval'), ('SUPERSEDED', 'Superseded')], default='DRAFT', max_length=30),
        ),
    ]
