# Generated by Django 6.1.1 on 2026-10-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_alter_generationrun_solver_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationrun',
            name='solver_status',
            field=models.CharField(blank=True, choices=[('OPTIMAL', 'Optimal'), ('FEASIBLE', 'Feasible'), ('INFEASIBLE', 'Infeasible'), ('MODEL_INVALID', 'Model Invalid'), ('UNKNOWN', 'Unknown'), ('PRECHECK_FAILED', 'Precheck Failed'), ('POST_VALIDATION_FAILED', 'Post Validation Failed')], max_length=32),
        ),
    ]
