# Generated by Django 6.1.1 on 2026-10-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_alter_generationrun_solver_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationrun',
            name='apply_validation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='generationrun',
            name='current_validation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='generationrun',
            name='generation_validation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='generationrun',
            name='input_fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='generationrun',
            name='input_snapshot_version',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
