# Generated by Django 6.1.1 on 2026-10-10 08:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_sectionweeklyoffpolicy_policy_type_and_more'),
        ('common', '0001_initial'),
        ('faculty', '0006_faculty_email'),
        ('rooms', '0009_alter_room_room_type'),
        ('scheduling', '0007_generationrun_apply_validation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporarySchedulePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('TRAINING', 'Training'), ('WORKSHOP', 'Workshop'), ('PLACEMENT', 'Placement'), ('SEMINAR', 'Seminar'), ('GUEST_LECTURE', 'Guest lecture'), ('EXAM_PREPARATION', 'Exam preparation'), ('SPECIAL_CLASS', 'Special class'), ('OTHER', 'Other')], default='OTHER', max_length=24)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=12)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('base_timetable_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temporary_plans', to='scheduling.timetableversion')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temporary_schedule_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemporaryScheduleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_date', models.DateField(blank=True, null=True)),
                ('weekday', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday')], null=True)),
                ('block_length', models.PositiveSmallIntegerField(default=1)),
                ('event_type', models.CharField(choices=[('TRAINING', 'Training'), ('WORKSHOP', 'Workshop'), ('PLACEMENT', 'Placement'), ('SEMINAR', 'Seminar'), ('GUEST_LECTURE', 'Guest lecture'), ('EXAM_PREPARATION', 'Exam preparation'), ('SPECIAL_CLASS', 'Special class'), ('OTHER', 'Other')], default='OTHER', max_length=24)),
                ('title', models.CharField(max_length=200)),
                ('trainer_name', models.CharField(blank=True, max_length=200)),
                ('delivery_mode', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], default='OFFLINE', max_length=10)),
                ('override_regular_class', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('faculty', models.ManyToManyField(blank=True, related_name='temporary_schedule_blocks', to='faculty.faculty')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='temporary_schedule_blocks', to='rooms.room')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_schedule_blocks', to='academics.section')),
                ('start_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temporary_schedule_blocks', to='common.timeslot')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='scheduling.temporaryscheduleplan')),
            ],
            options={
                'ordering': ['start_slot__order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TemporarySchedulePlanSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_links', to='scheduling.temporaryscheduleplan')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_plan_links', to='academics.section')),
            ],
        ),
        migrations.AddField(
            model_name='temporaryscheduleplan',
            name='sections',
            field=models.ManyToManyField(related_name='temporary_schedule_plans', through='scheduling.TemporarySchedulePlanSection', to='academics.section'),
        ),
        migrations.AddConstraint(
            model_name='temporaryscheduleplansection',
            constraint=models.UniqueConstraint(fields=('plan', 'section'), name='unique_temp_plan_section'),
        ),
    ]
