# Generated by Django 6.1.1 on 2026-10-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_temporaryscheduleplan_temporaryscheduleblock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryscheduleplan',
            name='published_impact',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
