'use client';

import { useEffect, useMemo, useState } from 'react';
import { Card, CardContent } from '@/components/ui/card';

type Offering = { course_offering_id:string; course_code:string; course_name:string; section_id:string; section:string; program:string; year:number; semester:string; session:string; activity_type:string; activity_type_label:string; required_periods:number; scheduled_periods:number; scheduled_classes:number; difference:number; completion_percentage:number|null; status:string; faculty:string[]; preferred_room:string; required_room_type:string; actual_rooms:string[]; delivery_modes:string[]; issues:string[] };
type Group = { offerings:number; required_periods:number; scheduled_periods:number; complete:number; under_scheduled:number; unscheduled:number; over_scheduled:number };
export type CourseAllocationPayload = { version:{title:string;session:string;semester:string}|null; summary:{total_offerings:number;fully_scheduled:number;under_scheduled:number;unscheduled:number;over_scheduled:number;required_periods:number;scheduled_periods:number;coverage_percentage:number;scheduled_classes:number}; offerings:Offering[]; needs_attention:Offering[]; status_distribution:{status:string;count:number}[]; program_summary:(Group&{program:string})[]; year_summary:(Group&{year:number})[]; program_year_summary:(Group&{program:string;year:number})[]; activity_summary:{activity_type:string;count:number}[]; section_coverage:{section_id:string;section:string;program:string;year:number;offering_count:number;required_periods:number;scheduled_periods:number;difference:number;completion_percentage:number|null}[]; faculty_allocations:{faculty:string;allocated_offerings:number;required_periods:number}[]; scope:{activity_type_data_quality:string} };
type Row = Record<string,unknown>;
const statusLabels:Record<string,string>={COMPLETE:'Complete',UNDER_SCHEDULED:'Under-Scheduled',UNSCHEDULED:'Unscheduled',OVER_SCHEDULED:'Over-Scheduled'};
const statusStyles:Record<string,string>={COMPLETE:'bg-emerald-50 text-emerald-800 border-emerald-200',UNDER_SCHEDULED:'bg-amber-50 text-amber-800 border-amber-200',UNSCHEDULED:'bg-rose-50 text-rose-800 border-rose-200',OVER_SCHEDULED:'bg-violet-50 text-violet-800 border-violet-200'};
const tableColumns:[keyof Offering,string][]=[['course_code','Course Code'],['course_name','Course Name'],['section','Section'],['program','Program'],['year','Year'],['semester','Semester'],['required_periods','Required Periods'],['scheduled_periods','Scheduled Periods'],['difference','Difference'],['completion_percentage','Completion %'],['status','Status'],['faculty','Faculty'],['activity_type_label','Activity Type'],['preferred_room','Preferred Room'],['actual_rooms','Actual Rooms']];
function Metric({label,value}:{label:string;value:string|number}){return <Card><CardContent className="p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></CardContent></Card>}
function BarLine({label,value,max,suffix=''}:{label:string;value:number;max:number;suffix?:string}){return <div className="grid grid-cols-[minmax(100px,1fr)_2fr_auto] items-center gap-3 text-sm"><span className="truncate" title={label}>{label}</span><span className="h-2 overflow-hidden rounded bg-slate-100"><span className="block h-full rounded bg-indigo-500" style={{width:`${Math.min(Math.max(value/max*100,0),100)}%`}}/></span><strong className="text-right tabular-nums">{value}{suffix}</strong></div>}
const list=(value:unknown)=>Array.isArray(value)?value.join(', '):String(value??'—');

export function CourseAllocationView({data,filters,filterOptions,onSelectSection}:{data:CourseAllocationPayload|null;filters:Record<string,string>;filterOptions?:Record<string,{value:string;label:string}[]>;onSelectSection:(id:string)=>void}){
  const [view,setView]=useState<'analytics'|'table'>('analytics');
  const [selected,setSelected]=useState<Offering|null>(null);
  const [sortKey,setSortKey]=useState<keyof Offering>('status');
  const [ascending,setAscending]=useState(true);
  useEffect(()=>{const print=()=>{setView('analytics');window.setTimeout(()=>window.print(),100)};window.addEventListener('course-allocation-print',print);return()=>window.removeEventListener('course-allocation-print',print)},[]);
  const rows=useMemo(()=>[...(data?.offerings??[])].sort((a,b)=>{const order={UNSCHEDULED:0,UNDER_SCHEDULED:1,OVER_SCHEDULED:2,COMPLETE:3};if(sortKey==='status')return (order[a.status as keyof typeof order]-order[b.status as keyof typeof order])||(ascending?`${a.program} ${a.year} ${a.section} ${a.course_code}`.localeCompare(`${b.program} ${b.year} ${b.section} ${b.course_code}`):`${b.program} ${b.year} ${b.section} ${b.course_code}`.localeCompare(`${a.program} ${a.year} ${a.section} ${a.course_code}`));const left=a[sortKey],right=b[sortKey];const compare=typeof left==='number'&&typeof right==='number'?left-right:String(left??'').localeCompare(String(right??''));return ascending?compare:-compare}),[data,sortKey,ascending]);
  if(!data)return <Card><CardContent className="p-8 text-center text-slate-500">No course allocation data is available in this scope.</CardContent></Card>;
  const summary=data.summary;
  const metrics=[['Total Course Offerings',summary.total_offerings],['Fully Scheduled',summary.fully_scheduled],['Under-Scheduled',summary.under_scheduled],['Over-Scheduled',summary.over_scheduled],['Unscheduled',summary.unscheduled],['Required Weekly Periods',summary.required_periods],['Scheduled Periods',summary.scheduled_periods],['Requirement Coverage',`${summary.coverage_percentage}%`]] as const;
  const print=()=>{setView('analytics');window.setTimeout(()=>window.print(),100)};
  return <div className="course-allocation-print-root space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm text-slate-500">Course offering coverage, scheduling completion, and allocation analytics.</p>{data.version&&<p className="mt-1 text-xs text-slate-400">{data.version.title} · {data.version.session} · {data.version.semester}</p>}</div><div className="no-print inline-flex rounded-lg border bg-white p-1 text-sm"><button onClick={()=>setView('analytics')} className={`rounded-md px-3 py-1.5 ${view==='analytics'?'bg-indigo-600 text-white':'text-slate-600'}`}>Analytics</button><button onClick={()=>setView('table')} className={`rounded-md px-3 py-1.5 ${view==='table'?'bg-indigo-600 text-white':'text-slate-600'}`}>Allocation Table</button></div></div>
    {view==='table'?<Card><CardContent className="overflow-x-auto p-0"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr>{tableColumns.map(([key,label])=><th className="whitespace-nowrap px-3 py-3" key={key}><button onClick={()=>sortKey===key?setAscending(!ascending):(setSortKey(key),setAscending(true))}>{label}{sortKey===key?(ascending?' ↑':' ↓'):''}</button></th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.course_offering_id} className="cursor-pointer border-t hover:bg-slate-50" onClick={()=>setSelected(row)}>{tableColumns.map(([key])=><td className="whitespace-nowrap px-3 py-3" key={key}>{key==='status'?<span className={`rounded-full border px-2 py-1 text-xs ${statusStyles[row.status]}`}>{statusLabels[row.status]}</span>:key==='completion_percentage'?(row.completion_percentage===null?'N/A':`${row.completion_percentage}%`):list(row[key])}</td>)}</tr>)}</tbody></table>{!rows.length&&<p className="p-8 text-center text-slate-500">No course offerings match these filters.</p>}</CardContent></Card>:<>
      <div className="hidden print:block"><h1 className="text-xl font-bold">BBD Smart Scheduler · Course Allocation Report</h1><p>Scope: {Object.entries(filters).filter(([,value])=>value).map(([key,value])=>`${key}: ${filterOptions?.[key]?.find(option=>option.value===value)?.label??value}`).join(' · ')||'Current published timetable'}</p></div>
      <div className="grid grid-cols-2 gap-3 md:grid-cols-4">{metrics.map(([label,value])=><Metric key={label} label={label} value={value}/>)}</div>
      <div className="grid gap-5 xl:grid-cols-2"><Card><CardContent className="p-5"><h2 className="font-semibold">Allocation Status Distribution</h2><div className="mt-4 space-y-3">{data.status_distribution.map(item=><BarLine key={item.status} label={statusLabels[item.status]??item.status} value={item.count} max={Math.max(1,summary.total_offerings)}/>)}</div></CardContent></Card><Card><CardContent className="p-5"><h2 className="font-semibold">Required vs Scheduled Periods</h2><div className="mt-4 space-y-3"><BarLine label="Required" value={summary.required_periods} max={Math.max(summary.required_periods,summary.scheduled_periods,1)}/><BarLine label="Scheduled" value={summary.scheduled_periods} max={Math.max(summary.required_periods,summary.scheduled_periods,1)}/></div><p className="mt-3 text-xs text-slate-500">Coverage is Σ min(scheduled, required) ÷ Σ required; over-scheduled periods do not offset gaps.</p></CardContent></Card></div>
      <div className="grid gap-5 xl:grid-cols-2"><Card><CardContent className="p-5"><h2 className="font-semibold">Offerings & Completion by Program</h2><div className="mt-4 max-h-[360px] space-y-3 overflow-y-auto">{data.program_summary.map(item=><div key={item.program} className="space-y-1"><div className="flex justify-between gap-3 text-sm"><strong className="truncate">{item.program}</strong><span>{item.offerings} offerings · {item.scheduled_periods}/{item.required_periods} periods</span></div><div className="flex h-3 overflow-hidden rounded bg-slate-100" aria-label={`${item.program}: ${item.complete} complete, ${item.under_scheduled} under-scheduled, ${item.unscheduled} unscheduled, ${item.over_scheduled} over-scheduled`}><span className="bg-emerald-500" style={{width:`${item.offerings?item.complete/item.offerings*100:0}%`}}/><span className="bg-amber-400" style={{width:`${item.offerings?item.under_scheduled/item.offerings*100:0}%`}}/><span className="bg-rose-500" style={{width:`${item.offerings?item.unscheduled/item.offerings*100:0}%`}}/><span className="bg-violet-500" style={{width:`${item.offerings?item.over_scheduled/item.offerings*100:0}%`}}/></div><p className="text-xs text-slate-500">Complete {item.complete} · Under {item.under_scheduled} · Unscheduled {item.unscheduled} · Over {item.over_scheduled}</p></div>)}</div></CardContent></Card><Card><CardContent className="p-5"><h2 className="font-semibold">Offerings by Activity Type</h2><div className="mt-4 space-y-3">{data.activity_summary.map(item=><BarLine key={item.activity_type} label={item.activity_type} value={item.count} max={Math.max(1,...data.activity_summary.map(row=>row.count))}/>)}</div><p className="mt-3 text-xs text-slate-500">{data.scope.activity_type_data_quality}</p></CardContent></Card></div>
      <div className="grid gap-5 xl:grid-cols-2"><Card><CardContent className="p-5"><h2 className="font-semibold">Program → Year Allocation</h2><div className="mt-4 max-h-[360px] space-y-2 overflow-y-auto">{data.program_year_summary.map(item=><div className="grid grid-cols-[1fr_auto_auto] gap-3 border-b py-2 text-sm" key={`${item.program}:${item.year}`}><span>{item.program} · Year {item.year}</span><span>{item.offerings} offerings</span><strong>{item.scheduled_periods}/{item.required_periods} periods</strong></div>)}</div></CardContent></Card><Card><CardContent className="p-5"><h2 className="font-semibold">Offerings by Year</h2><div className="mt-4 space-y-3">{data.year_summary.map(item=><div key={item.year}><BarLine label={`Year ${item.year}`} value={item.offerings} max={Math.max(1,...data.year_summary.map(row=>row.offerings))}/><p className="mt-1 pl-1 text-xs text-slate-500">{item.scheduled_periods}/{item.required_periods} periods · Complete {item.complete} · Under {item.under_scheduled} · Unscheduled {item.unscheduled} · Over {item.over_scheduled}</p></div>)}</div></CardContent></Card></div>
      <Card><CardContent className="p-5"><h2 className="font-semibold">Section Coverage · Select a section to filter</h2><div className="mt-4 max-h-[360px] overflow-auto"><table className="w-full text-left text-sm"><thead className="sticky top-0 bg-white text-xs text-slate-500"><tr>{['Section','Offerings','Required','Scheduled','Coverage'].map(label=><th className="py-2" key={label}>{label}</th>)}</tr></thead><tbody>{data.section_coverage.map(item=><tr className="border-t" key={item.section_id}><td className="py-2"><button className="text-left hover:text-indigo-700 hover:underline" onClick={()=>onSelectSection(item.section_id)}>{item.section} · {item.program} Year {item.year}</button></td><td>{item.offering_count}</td><td>{item.required_periods}</td><td>{item.scheduled_periods}</td><td>{item.completion_percentage===null?'N/A':`${item.completion_percentage}%`}</td></tr>)}</tbody></table></div></CardContent></Card>
      <div className="grid gap-5 xl:grid-cols-2"><Card><CardContent className="p-5"><h2 className="font-semibold">Needs Attention</h2><p className="text-xs text-slate-500">Unscheduled, under/over-scheduled, or without a faculty assignment. Advisories do not alter source data.</p><div className="mt-3 max-h-[420px] overflow-auto"><table className="w-full text-left text-sm"><thead className="sticky top-0 bg-white text-xs text-slate-500"><tr><th className="py-2">Offering</th><th>Section</th><th>Req.</th><th>Sched.</th><th>Issue</th></tr></thead><tbody>{data.needs_attention.map(row=><tr key={row.course_offering_id} className="cursor-pointer border-t" onClick={()=>setSelected(row)}><td className="py-2"><strong>{row.course_code}</strong><span className="block text-xs text-slate-500">{row.course_name}</span></td><td>{row.section}</td><td>{row.required_periods}</td><td>{row.scheduled_periods}</td><td>{row.issues.join('; ')}</td></tr>)}</tbody></table>{!data.needs_attention.length&&<p className="p-4 text-sm text-emerald-700">No offerings require attention in this scope.</p>}</div></CardContent></Card><Card><CardContent className="p-5"><h2 className="font-semibold">Faculty Allocated Offerings</h2><p className="text-xs text-slate-500">Distinct course offerings and their required periods—not actual teaching workload.</p><div className="mt-3 max-h-[420px] space-y-2 overflow-y-auto">{data.faculty_allocations.map(item=><div className="grid grid-cols-[1fr_auto_auto] gap-3 border-b py-2 text-sm" key={item.faculty}><span>{item.faculty}</span><strong>{item.allocated_offerings} offerings</strong><span>{item.required_periods} required periods</span></div>)}</div></CardContent></Card></div>
      <Card><CardContent className="p-5"><h2 className="font-semibold">Required vs Scheduled by Offering</h2><p className="mb-3 text-xs text-slate-500">Full filtered offering list, including completed offerings and zero-schedule requirements.</p><div className="max-h-[560px] space-y-2 overflow-y-auto">{data.offerings.map(row=><button key={row.course_offering_id} onClick={()=>setSelected(row)} className="grid w-full grid-cols-[minmax(150px,1fr)_100px_100px_minmax(100px,1fr)] items-center gap-3 rounded border p-2 text-left text-sm hover:bg-slate-50"><span className="truncate"><strong>{row.course_code}</strong> · {row.section}</span><span>Req. {row.required_periods}</span><span>Sched. {row.scheduled_periods}</span><span className="flex items-center gap-2"><span className="h-2 flex-1 rounded bg-slate-100"><span className="block h-2 rounded bg-indigo-500" style={{width:`${Math.min(row.completion_percentage??0,100)}%`}}/></span><span>{row.completion_percentage===null?'N/A':`${row.completion_percentage}%`}</span></span></button>)}</div></CardContent></Card>
    </>}
    {selected&&<div className="no-print fixed inset-0 z-50 flex justify-end bg-slate-900/30" onClick={()=>setSelected(null)}><section className="h-full w-full max-w-lg overflow-y-auto bg-white p-6 shadow-xl" onClick={event=>event.stopPropagation()}><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">{selected.course_code} · Offering details</h2><button className="rounded border px-3 py-1" onClick={()=>setSelected(null)}>Close</button></div><p className="mt-1 text-sm text-slate-500">{selected.course_name}</p><p className="mt-2"><span className={`rounded-full border px-2 py-1 text-xs ${statusStyles[selected.status]}`}>{statusLabels[selected.status]}</span></p><dl className="mt-5 grid grid-cols-2 gap-4 text-sm">{[['Program',selected.program],['Section',selected.section],['Year',selected.year],['Semester',selected.semester],['Academic Session',selected.session],['Required Weekly Periods',selected.required_periods],['Scheduled Periods',selected.scheduled_periods],['Difference',selected.difference],['Completion',selected.completion_percentage===null?'N/A':`${selected.completion_percentage}%`],['Activity Type',selected.activity_type_label],['Faculty',list(selected.faculty)],['Preferred Room',selected.preferred_room||'—'],['Required Room Type',selected.required_room_type||'—'],['Actual Rooms',list(selected.actual_rooms)],['Delivery Modes',list(selected.delivery_modes)],['Scheduled Classes',selected.scheduled_classes]].map(([label,value])=><div key={String(label)}><dt className="text-xs text-slate-500">{label}</dt><dd className="break-words font-medium">{String(value??'—')}</dd></div>)}</dl><details className="mt-5 text-xs text-slate-500"><summary className="cursor-pointer">Advanced details</summary><p className="mt-2 break-all">CourseOffering ID: {selected.course_offering_id}</p></details></section></div>}
  </div>;
}
