'use client';

import { useEffect, useMemo, useState } from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { apiClient } from '@/lib/api/client';

type Faculty = { faculty_id: string; faculty_name: string; employee_code: string; department: string; teaching_periods: number; scheduled_classes: number; distinct_courses: number; distinct_sections: number };
type Entry = { entry_id: string; section_id: string; section: string; program: string; year: number; semester: string; session: string; day: string; weekday: number; course_code: string; course_name: string; room: string; delivery_mode: string; block_length: number; start_slot_id: string; template_id: string; start_time: string; end_time: string; occupied_slot_ids: string[]; availability_conflict: boolean };
type Slot = { id: string; template_id: string; label: string; start_time: string; end_time: string; order: number; is_break: boolean };
type Metric = { scheduled_classes: number; teaching_periods: number; distinct_courses: number; distinct_sections: number; rooms_used: number; teaching_days: number; online_periods: number; offline_periods: number; busiest_day: {day:string;periods:number}|null; lightest_teaching_day: {day:string;periods:number}|null; free_available_periods: number; unavailable_periods: number; break_periods: number };
export type FacultyTimetablePayload = { version: {title:string;session:string;semester:string}|null; selected_faculty: {id:string;name:string;employee_code:string;department:string}|null; summary: Record<string, unknown>|null; entries: Entry[]; faculties: Faculty[]; slots: Slot[]; availability_states: {weekday:number;slot_id:string;state:string}[]; availability: {configured:boolean;configuration_complete:boolean;configured_slots:number;teaching_slots:number;free_periods:number;unavailable_periods:number;break_periods:number;message:string}; day_load: {weekday:number;day:string;periods:number}[]; course_load: {course_id:string;course_code:string;course_name:string;periods:number;sections:number}[]; section_load: {section_id:string;section:string;program:string;year:number;periods:number}[]; room_load: {room_id:string|null;room:string;periods:number;delivery_mode:string}[]; workload_distribution: {range:string;faculty_count:number}[] };
type Row = Record<string, unknown>;
const days = ['Monday','Tuesday','Wednesday','Thursday','Friday'];
const columns = [['day','Day'],['start_time','Start Time'],['end_time','End Time'],['course_code','Course Code'],['course_name','Course Name'],['section','Section'],['program','Program'],['year','Year'],['semester','Semester'],['room','Room'],['delivery_mode','Delivery Mode'],['block_length','Block Length']] as const;
const text = (value: unknown) => String(value ?? '—');

function MetricCard({label,value}:{label:string;value:string|number}) { return <Card><CardContent className="p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-xl font-semibold text-slate-900">{value}</p></CardContent></Card>; }

export function FacultyTimetableView({data,facultyId,onSelectFaculty,filters}:{data:FacultyTimetablePayload|null;facultyId:string;onSelectFaculty:(id:string)=>void;filters:Record<string,string>}) {
  const [view,setView]=useState<'visual'|'table'>('visual');
  const [detail,setDetail]=useState<Entry|null>(null);
  const [tableRows,setTableRows]=useState<Row[]>([]);
  const [tableLoading,setTableLoading]=useState(false);
  const faculty=data?.selected_faculty;
  const summary=(data?.summary??{}) as Partial<Metric>&Record<string,unknown>;
  const isOverview=!facultyId;
  const states=useMemo(()=>new Map((data?.availability_states??[]).map(item=>[`${item.weekday}:${item.slot_id}`,item.state])),[data]);
  const occupied=useMemo(()=>{const map=new Map<string,Entry>();for(const entry of data?.entries??[])for(const id of entry.occupied_slot_ids)map.set(`${entry.weekday}:${id}`,entry);return map;},[data]);
  useEffect(()=>{if(view!=='table')return;const controller=new AbortController();setTableLoading(true);const params=Object.fromEntries(Object.entries(filters).filter(([,value])=>value));apiClient.get('/reports/faculty-timetable/',{params,signal:controller.signal}).then(({data:response})=>setTableRows(Array.isArray(response)?response as Row[]:[])).catch(()=>{if(!controller.signal.aborted)setTableRows([])}).finally(()=>{if(!controller.signal.aborted)setTableLoading(false)});return()=>controller.abort();},[view,filters]);
  useEffect(()=>{const print=()=>{setView('visual');window.setTimeout(()=>window.print(),120)};window.addEventListener('faculty-report-print',print);return()=>window.removeEventListener('faculty-report-print',print)},[]);
  if(!data)return <Card><CardContent className="p-8 text-center text-slate-500">No current published timetable is available.</CardContent></Card>;
  const summaryCards=isOverview?[
    ['Faculty with Published Classes',summary.faculty_with_published_classes??0],['Total Teaching Periods',summary.total_teaching_periods??0],['Average Teaching Load',summary.average_teaching_load??0],['Maximum Teaching Load',summary.maximum_teaching_load??0],['Faculty With Zero Published Load',summary.faculty_with_zero_published_load??0],['Total Distinct Courses',summary.total_distinct_courses??0]
  ]:[['Scheduled Classes',summary.scheduled_classes??0],['Teaching Periods',summary.teaching_periods??0],['Distinct Courses',summary.distinct_courses??0],['Distinct Sections',summary.distinct_sections??0],['Rooms Used',summary.rooms_used??0],['Teaching Days',summary.teaching_days??0],['Free Available Periods',summary.free_available_periods??'—'],['Busiest Day',summary.busiest_day?`${(summary.busiest_day as {day:string;periods:number}).day} · ${(summary.busiest_day as {day:string;periods:number}).periods}`:'—']];
  const stateLabel=(state:string)=>state==='BREAK'?'LUNCH / BREAK':state==='UNAVAILABLE'?'Unavailable':state==='NOT_CONFIGURED'?'Not configured':'Free';
  const cell=(weekday:number,slot:Slot,index:number)=>{const entry=occupied.get(`${weekday}:${slot.id}`);const covered=data.entries.some(item=>item.weekday===weekday&&item.entry_id===entry?.entry_id&&item.occupied_slot_ids.some(id=>id===data.slots[index-1]?.id));if(covered)return null;if(entry){const positions=entry.occupied_slot_ids.map(id=>data.slots.findIndex(item=>item.id===id)).filter(position=>position>=index);const span=Math.max(positions.length?positions.at(-1)!-index+1:1,1);return <button key={slot.id} onClick={()=>setDetail(entry)} className={`faculty-entry-cell ${entry.availability_conflict?'border-amber-400 bg-amber-50':'border-indigo-200 bg-indigo-50'}`} style={{gridColumn:`${index+1}/span ${span}`}}><strong className="block text-indigo-950">{entry.course_code}</strong><span className="block truncate font-medium">{entry.course_name}</span><span className="mt-1 block truncate">{entry.section} · Year {entry.year}</span><span className="mt-1 flex flex-wrap gap-1"><span className="rounded bg-white px-1.5 py-0.5">{entry.delivery_mode}</span>{entry.delivery_mode==='OFFLINE'&&entry.room&&<span className="rounded bg-white px-1.5 py-0.5">Room {entry.room}</span>}</span>{entry.availability_conflict&&<span className="mt-1 block font-semibold text-amber-800">⚠ Scheduled — Availability Conflict</span>}<span className="mt-1 block text-slate-500">{entry.start_time}–{entry.end_time} · {entry.block_length} period(s)</span></button>}
    const state=states.get(`${weekday}:${slot.id}`)??(slot.is_break?'BREAK':'NOT_CONFIGURED');return <div key={slot.id} className={`faculty-empty-cell ${state==='BREAK'?'bg-slate-100 font-semibold text-slate-600':state==='UNAVAILABLE'?'border-amber-200 bg-amber-50 text-amber-800':state==='FREE'?'bg-white text-slate-500':'bg-slate-50 text-slate-400'}`}>{stateLabel(state)}</div>};
  return <div className="faculty-print-root space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm text-slate-500">Visual teaching schedule and workload derived from the current published timetable.</p>{data.version&&<p className="mt-1 text-xs text-slate-400">{data.version.title} · {data.version.session} · {data.version.semester}</p>}</div><div className="no-print inline-flex rounded-lg border bg-white p-1 text-sm"><button onClick={()=>setView('visual')} className={`rounded-md px-3 py-1.5 ${view==='visual'?'bg-indigo-600 text-white':'text-slate-600'}`}>Visual Timetable</button><button onClick={()=>setView('table')} className={`rounded-md px-3 py-1.5 ${view==='table'?'bg-indigo-600 text-white':'text-slate-600'}`}>Table View</button></div></div>
    {view==='table'?<Card><CardContent className="overflow-x-auto p-0"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr>{columns.map(([,label])=><th className="whitespace-nowrap px-4 py-3" key={label}>{label}</th>)}</tr></thead><tbody>{tableRows.map((row,index)=><tr className="border-t" key={String(row.entry_id??index)}>{columns.map(([key])=><td className="whitespace-nowrap px-4 py-3" key={key}>{String(row[key]??'')}</td>)}</tr>)}</tbody></table>{tableLoading&&<p className="p-5 text-center text-slate-500">Loading timetable rows…</p>}{!tableLoading&&!tableRows.length&&<p className="p-8 text-center text-slate-500">No scheduled entries match these filters.</p>}</CardContent></Card>:<>
      {!isOverview&&faculty&&<div className="faculty-print-heading hidden print:block"><h1>BBD Smart Scheduler · Faculty Timetable</h1><p>Faculty: {faculty.name} · Employee Code: {faculty.employee_code||'—'} · Department: {faculty.department}</p><p>Academic Session: {data.version?.session??'—'} · Semester: {data.version?.semester??'—'}</p></div>}
      <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 xl:grid-cols-6">{summaryCards.map(([label,value])=><MetricCard key={String(label)} label={String(label)} value={String(value)}/>)}</div>
      {isOverview?<>
        <Card><CardContent className="p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Faculty analytics overview</h2><p className="text-sm text-slate-500">Select a faculty member to open their detailed weekly timetable.</p></div><label className="text-sm">Compare by<select className="ml-2 rounded border bg-white px-3 py-2" value="periods" onChange={()=>undefined}><option value="periods">Teaching periods</option></select></label></div><div className="mt-4 max-h-[520px] space-y-2 overflow-y-auto">{data.faculties.map(item=>{const max=Math.max(1,...data.faculties.map(row=>row.teaching_periods));return <button key={item.faculty_id} onClick={()=>onSelectFaculty(item.faculty_id)} className="grid w-full grid-cols-[minmax(180px,1.2fr)_2fr_55px] items-center gap-3 rounded-lg border border-slate-100 p-3 text-left hover:border-indigo-200 hover:bg-indigo-50/40"><span className="min-w-0"><strong className="block truncate">{item.faculty_name}</strong><span className="block truncate text-xs text-slate-500">{item.employee_code} · {item.department} · {item.distinct_courses} courses · {item.distinct_sections} sections</span></span><span className="h-2 overflow-hidden rounded bg-slate-100"><span className="block h-full rounded bg-indigo-500" style={{width:`${item.teaching_periods/max*100}%`}}/></span><span className="text-right text-sm font-semibold">{item.teaching_periods}</span></button>})}</div></CardContent></Card>
        <div className="grid gap-5 lg:grid-cols-2"><Card><CardContent className="p-5"><h2 className="font-semibold">Workload distribution</h2>{(data.workload_distribution??[]).map(item=><div className="mt-3 flex justify-between text-sm" key={item.range}><span>{item.range}</span><strong>{item.faculty_count} faculty</strong></div>)}</CardContent></Card><Card><CardContent className="p-5"><h2 className="font-semibold">Day-wise faculty teaching load</h2>{data.day_load.map(item=>{const max=Math.max(1,...data.day_load.map(day=>day.periods));return <div className="mt-3 grid grid-cols-[90px_1fr_50px] items-center gap-3 text-sm" key={item.weekday}><span>{item.day}</span><span className="h-2 rounded bg-slate-100"><span className="block h-2 rounded bg-indigo-500" style={{width:`${item.periods/max*100}%`}}/></span><strong className="text-right">{item.periods}</strong></div>})}</CardContent></Card></div>
      </>:<>
        <Card><CardContent className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">{faculty?.name}</h2><p className="text-sm text-slate-500">{faculty?.employee_code||'No employee code'} · {faculty?.department}</p></div>{!data.availability.configuration_complete&&<p className="max-w-xl rounded border border-amber-200 bg-amber-50 p-2 text-xs text-amber-800">{data.availability.message||'Faculty availability is not fully configured; unconfigured periods are identified separately.'}</p>}</div><h3 className="mb-3 mt-5 font-semibold">Weekly timetable</h3><div className="hidden overflow-x-auto md:block"><div className="min-w-[900px]"><div className="grid border-b bg-slate-50" style={{gridTemplateColumns:`95px repeat(${data.slots.length},minmax(95px,1fr))`}}><div className="p-2 text-xs font-semibold">Day</div>{data.slots.map(slot=><div key={slot.id} className="border-l p-2 text-center text-xs">{slot.label}</div>)}</div>{data.day_load.map(({weekday,day})=><div key={day} className="grid border-b" style={{gridTemplateColumns:`95px repeat(${data.slots.length},minmax(95px,1fr))`}}><div className="bg-slate-50 p-3 text-sm font-medium">{day}</div>{data.slots.map((slot,index)=>cell(weekday,slot,index))}</div>)}</div></div><div className="space-y-4 md:hidden">{data.day_load.map(({weekday,day})=><section key={day} className="rounded-lg border p-3"><h3 className="mb-2 font-semibold">{day}</h3><div className="space-y-2">{data.slots.map((slot,index)=>{const entry=occupied.get(`${weekday}:${slot.id}`);const covered=entry&&data.slots.slice(0,index).some(previous=>occupied.get(`${weekday}:${previous.id}`)?.entry_id===entry.entry_id);if(covered)return null;if(entry)return <button key={slot.id} onClick={()=>setDetail(entry)} className={`block w-full rounded border p-3 text-left ${entry.availability_conflict?'border-amber-300 bg-amber-50':'border-indigo-200 bg-indigo-50'}`}><span className="text-xs text-slate-500">{entry.start_time}–{entry.end_time}</span><strong className="block">{entry.course_code} · {entry.course_name}</strong><span className="block text-sm">{entry.section} · {entry.delivery_mode}{entry.delivery_mode==='OFFLINE'&&entry.room?` · Room ${entry.room}`:''}</span>{entry.availability_conflict&&<span className="text-xs font-semibold text-amber-800">Scheduled — Availability Conflict</span>}</button>;const state=states.get(`${weekday}:${slot.id}`)??(slot.is_break?'BREAK':'NOT_CONFIGURED');return <div key={slot.id} className="rounded border p-2 text-sm">{slot.label} · {stateLabel(state)}</div>})}</div></section>)}</div></CardContent></Card>
        <div className="grid gap-5 lg:grid-cols-2"><Card><CardContent className="p-5"><h2 className="font-semibold">Teaching Load by Day</h2>{data.day_load.map(item=><div className="mt-3 flex justify-between text-sm" key={item.weekday}><span>{item.day}</span><strong>{item.periods} periods</strong></div>)}<p className="mt-3 border-t pt-3 text-xs text-slate-500">Lightest teaching day: {summary.lightest_teaching_day?`${(summary.lightest_teaching_day as {day:string;periods:number}).day} · ${(summary.lightest_teaching_day as {day:string;periods:number}).periods} periods`:'—'}</p><p className="mt-1 text-xs text-slate-500">Online: {summary.online_periods??0} · Offline: {summary.offline_periods??0}</p></CardContent></Card><Card><CardContent className="p-5"><h2 className="font-semibold">Courses Taught</h2>{data.course_load.map(row=><div className="mt-3 flex justify-between gap-3 border-b pb-2 text-sm" key={row.course_id}><span><strong>{row.course_code}</strong><span className="block text-xs text-slate-500">{row.course_name} · {row.sections} sections</span></span><strong className="whitespace-nowrap">{row.periods} periods</strong></div>)}</CardContent></Card><Card><CardContent className="p-5"><h2 className="font-semibold">Sections Taught</h2>{data.section_load.map(row=><div className="mt-2 flex justify-between text-sm" key={row.section_id}><span>{row.section} · {row.program} Year {row.year}</span><strong>{row.periods} periods</strong></div>)}</CardContent></Card><Card><CardContent className="p-5"><h2 className="font-semibold">Room Usage by Faculty</h2>{data.room_load.map(row=><div className="mt-2 flex justify-between text-sm" key={`${row.delivery_mode}:${row.room_id??row.room}`}><span>{row.delivery_mode==='ONLINE'?'ONLINE':`Room ${row.room}`}</span><strong>{row.periods} periods</strong></div>)}</CardContent></Card></div>
      </>}
    </>}
    {detail&&<div className="no-print fixed inset-0 z-50 flex justify-end bg-slate-900/30" onClick={()=>setDetail(null)}><section className="h-full w-full max-w-md overflow-y-auto bg-white p-6 shadow-xl" onClick={event=>event.stopPropagation()}><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">Class details</h2><button className="rounded border px-3 py-1" onClick={()=>setDetail(null)}>Close</button></div><dl className="mt-5 space-y-3 text-sm">{[['Faculty',faculty?.name],['Day',detail.day],['Start Time',detail.start_time],['End Time',detail.end_time],['Course Code',detail.course_code],['Course Name',detail.course_name],['Section',detail.section],['Program',detail.program],['Year',detail.year],['Semester',detail.semester],['Academic Session',detail.session],['Room',detail.delivery_mode==='ONLINE'?'No room (online)':detail.room||'Not assigned'],['Delivery Mode',detail.delivery_mode],['Block Length',`${detail.block_length} period(s)`]].map(([label,value])=><div key={String(label)}><dt className="text-xs text-slate-500">{label}</dt><dd className="font-medium">{text(value)}</dd></div>)}</dl></section></div>}
  </div>;
}
