'use client';

import { Card, CardContent } from '@/components/ui/card';

type Room={room_id:string;room_no:string;room_type:string;capacity:number;building:string;floor:string;projector:string};
type Chart={label:string;count:number};
export type FreeRoomsPayload={version:{id:string;title:string;session:string;semester:string}|null;requested_slot:string|null;weekday:number|null;message?:string;summary:{free_rooms:number;projector_available:number;average_capacity:number;largest_capacity:number};analytics:{by_room_type:Chart[];by_building:Chart[];capacity_distribution:Chart[]};audit:{active_rooms:number;occupied_rooms:number;blocked_rooms:number;free_rooms:number;occupied_codes:string[];blocked_codes:string[];free_codes:string[]};rooms:Room[]};
function Chart({title,rows}:{title:string;rows:Chart[]}){const max=Math.max(1,...rows.map(row=>row.count));return <Card><CardContent className="p-5"><h2 className="font-semibold">{title}</h2><div className="mt-4 space-y-3">{rows.map(row=><div className="grid grid-cols-[minmax(90px,1fr)_2fr_auto] items-center gap-3 text-sm" key={row.label}><span>{row.label}</span><div className="h-2 rounded bg-slate-100"><div className="h-2 rounded bg-indigo-500" style={{width:`${row.count/max*100}%`}}/></div><strong>{row.count}</strong></div>)}</div></CardContent></Card>}
export function FreeRoomsView({data}:{data:FreeRoomsPayload|null}){if(!data)return <p>Unable to load free rooms.</p>;const metrics=[['Free Rooms',data.summary.free_rooms],['Projector Available',data.summary.projector_available],['Average Capacity',data.summary.average_capacity],['Largest Free Room Capacity',data.summary.largest_capacity]] as const;return <div className="free-rooms-print-root space-y-5"><header><h1 className="text-2xl font-semibold">BBD Smart Scheduler · Free Rooms</h1><p className="mt-1 text-sm text-slate-500">{data.version?`${data.version.title} · ${data.version.session} · ${data.version.semester}`:'No published timetable'}{data.requested_slot?` · ${['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'][data.weekday??0]} ${data.requested_slot}`:''}</p></header>{data.message&&<Card><CardContent className="p-5 text-amber-800">{data.message}</CardContent></Card>}<div className="grid grid-cols-2 gap-3 xl:grid-cols-4">{metrics.map(([label,value])=><Card key={label}><CardContent className="p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></CardContent></Card>)}</div><div className="grid gap-4 xl:grid-cols-2"><Chart title="Free Rooms by Room Type" rows={data.analytics.by_room_type}/><Chart title="Projector Availability" rows={[{label:'Available',count:data.summary.projector_available},{label:'Not Available',count:data.summary.free_rooms-data.summary.projector_available}]}/><Chart title="Free Rooms by Building" rows={data.analytics.by_building}/><Chart title="Capacity Distribution" rows={data.analytics.capacity_distribution}/></div><Card><CardContent className="p-5"><h2 className="font-semibold">Room Availability Audit</h2><p className="mt-2 text-sm text-slate-600">Active {data.audit.active_rooms} · Occupied {data.audit.occupied_rooms} · Blocked / maintenance {data.audit.blocked_rooms} · Free {data.audit.free_rooms}</p><p className="mt-1 break-words text-xs text-slate-500">Occupied: {data.audit.occupied_codes.join(', ')||'None'}</p><p className="mt-1 break-words text-xs text-slate-500">Blocked: {data.audit.blocked_codes.join(', ')||'None'}</p></CardContent></Card><Card><CardContent className="overflow-x-auto p-0"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr>{['Room','Room Type','Building','Floor','Capacity','Projector'].map(label=><th className="px-4 py-3" key={label}>{label}</th>)}</tr></thead><tbody>{data.rooms.map(room=><tr className="border-t" key={room.room_id}><td className="px-4 py-3">{room.room_no}</td><td className="px-4 py-3">{room.room_type}</td><td className="px-4 py-3">{room.building}</td><td className="px-4 py-3">{room.floor}</td><td className="px-4 py-3">{room.capacity}</td><td className="px-4 py-3">{room.projector}</td></tr>)}</tbody></table>{!data.rooms.length&&!data.message&&<p className="p-8 text-center">No rooms match this search.</p>}</CardContent></Card></div>}
