'use client';

import { useMemo, useState } from 'react';
import { Card, CardContent } from '@/components/ui/card';

type Offering = { course_offering_id:string; course_code:string; course_name:string; section:string; section_id:string; program:string; year:number; semester:string; session:string; required_periods:number; scheduled_periods:number; difference:number; status:string; faculty:string[]; activity_type_label:string; required_room_type:string; preferred_room:string; actual_rooms:string[]; delivery_modes:string[] };
export type GapPayload = { summary:{total_offerings:number;incomplete_offerings:number;unscheduled_offerings:number;partially_scheduled:number;over_scheduled:number;required_periods:number;scheduled_periods:number;remaining_periods:number;coverage_percentage:number;affected_sections:number}; version:{title:string;session:string;semester:string}|null; offerings:Offering[]; status_distribution:{status:string;count:number}[]; remaining_by_section:{section_id:string;section:string;program:string;year:number;remaining_periods:number;offerings:number}[]; remaining_by_program:{program:string;remaining_periods:number}[]; remaining_by_year:{year:number;remaining_periods:number}[]; remaining_by_activity:{activity_type:string;remaining_periods:number}[]; faculty_gaps:{faculty:string;remaining_periods:number;offerings:number}[]; offerings_without_faculty:Offering[]; scope_has_offerings:boolean };

const statusLabel=(status:string)=>status==='UNSCHEDULED'?'Unscheduled':status==='UNDER_SCHEDULED'?'Partially Scheduled':status==='OVER_SCHEDULED'?'Over-Scheduled':'Complete';
function Bars({title,items}:{title:string;items:{label:string;value:number;action?:()=>void}[]}){const max=Math.max(1,...items.map(item=>item.value));return <Card><CardContent className="p-5"><h2 className="font-semibold">{title}</h2><div className="mt-4 max-h-80 space-y-3 overflow-y-auto">{items.map(item=><button className="grid w-full grid-cols-[minmax(80px,1fr)_2fr_auto] items-center gap-3 text-left text-sm" key={item.label} onClick={item.action}><span className="truncate">{item.label}</span><span className="h-2 rounded bg-slate-100"><span className="block h-2 rounded bg-indigo-500" style={{width:`${item.value/max*100}%`}}/></span><strong>{item.value}</strong></button>)}{!items.length&&<p className="text-sm text-slate-500">No scheduling gaps in this scope.</p>}</div></CardContent></Card>}

export function UnscheduledClassesView({data,onSelectSection}:{data:GapPayload|null;onSelectSection:(id:string)=>void}){
 const [selected,setSelected]=useState<Offering|null>(null),[section,setSection]=useState('');
 const rows=useMemo(()=>data?.offerings.filter(row=>!section||row.section_id===section)??[],[data,section]);
 if(!data)return <p>Unable to load scheduling gaps.</p>;
 const s=data.summary;
 const metrics=[['Incomplete Offerings',s.incomplete_offerings],['Completely Unscheduled',s.unscheduled_offerings],['Partially Scheduled',s.partially_scheduled],['Remaining Periods',s.remaining_periods],['Coverage',`${s.coverage_percentage}%`],['Affected Sections',s.affected_sections]] as const;
 return <div className="unscheduled-print-root space-y-5"><header className="unscheduled-print-title"><h1 className="text-2xl font-semibold">BBD Smart Scheduler · Unscheduled Classes</h1><p className="mt-1 text-sm text-slate-500">Published scope: {data.version?`${data.version.title} · ${data.version.session} · ${data.version.semester}`:'No published timetable'}</p></header>
 <div className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-6">{metrics.map(([label,value])=><Card key={label}><CardContent className="p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></CardContent></Card>)}</div>
 {!data.scope_has_offerings?<Card><CardContent className="p-8 text-center"><h2 className="text-lg font-semibold">No CourseOfferings exist for the selected filters.</h2></CardContent></Card>:s.incomplete_offerings===0?<Card className="border-emerald-200 bg-emerald-50"><CardContent className="p-8 text-center"><h2 className="text-xl font-semibold text-emerald-900">✓ All course offerings are fully scheduled</h2><p className="mt-2 text-sm text-emerald-800">All required weekly periods have been placed in the current published timetable for the selected scope.</p><p className="mt-3 text-sm">{s.total_offerings} offerings · {s.required_periods} required periods · {s.scheduled_periods} scheduled periods · {s.coverage_percentage}% coverage</p></CardContent></Card>:null}
 <div className="grid gap-4 xl:grid-cols-2"><Card><CardContent className="p-5"><h2 className="font-semibold">Required vs Scheduled vs Remaining</h2><div className="mt-4 grid grid-cols-3 gap-3 text-center"><div><p className="text-xs text-slate-500">Required</p><strong className="text-xl">{s.required_periods}</strong></div><div><p className="text-xs text-slate-500">Scheduled</p><strong className="text-xl">{s.scheduled_periods}</strong></div><div><p className="text-xs text-slate-500">Remaining</p><strong className="text-xl">{s.remaining_periods}</strong></div></div><div className="mt-4 h-4 overflow-hidden rounded bg-slate-100"><div className="h-full bg-indigo-500" style={{width:`${Math.min(s.coverage_percentage,100)}%`}}/></div><p className="mt-2 text-xs text-slate-500">Coverage counts no more than each offering’s required periods.</p></CardContent></Card>
 <Card><CardContent className="p-5"><h2 className="font-semibold">Overall Status Distribution</h2><div className="mt-4 grid grid-cols-2 gap-3">{data.status_distribution.map(item=><div className="rounded border p-3" key={item.status}><span className="text-sm">{statusLabel(item.status)}</span><strong className="float-right">{item.count}</strong></div>)}</div></CardContent></Card></div>
 <div className="grid gap-4 xl:grid-cols-2"><Bars title="Remaining Periods by Section" items={data.remaining_by_section.map(item=>({label:`${item.section} · ${item.program}`,value:item.remaining_periods,action:()=>{setSection(item.section_id);onSelectSection(item.section_id)}}))}/><Bars title="Remaining Periods by Program" items={data.remaining_by_program.map(item=>({label:item.program,value:item.remaining_periods}))}/><Bars title="Remaining Periods by Year" items={data.remaining_by_year.map(item=>({label:`Year ${item.year}`,value:item.remaining_periods}))}/><Bars title="Scheduling Gap by Activity Type" items={data.remaining_by_activity.map(item=>({label:item.activity_type,value:item.remaining_periods}))}/><Bars title="Incomplete Offerings by Faculty" items={data.faculty_gaps.map(item=>({label:`${item.faculty} · ${item.offerings} offerings`,value:item.remaining_periods}))}/><Card><CardContent className="p-5"><h2 className="font-semibold">Offerings Missing Faculty Assignment</h2><div className="mt-3 max-h-72 space-y-2 overflow-y-auto">{data.offerings_without_faculty.map(row=><button key={row.course_offering_id} onClick={()=>setSelected(row)} className="block w-full rounded border p-3 text-left text-sm">{row.course_code} · {row.section} · {row.required_periods} required</button>)}{!data.offerings_without_faculty.length&&<p className="text-sm text-slate-500">No incomplete offerings are missing faculty.</p>}</div></CardContent></Card></div>
 <Card><CardContent className="overflow-x-auto p-0"><div className="flex items-center justify-between p-4"><h2 className="font-semibold">Needs Attention</h2>{section&&<button className="no-print text-sm text-indigo-700" onClick={()=>{setSection('');onSelectSection('')}}>Clear section selection</button>}</div><table className="w-full min-w-[950px] text-left text-sm"><thead className="bg-slate-50"><tr>{['Status','Course','Name','Section','Program / Year','Required','Scheduled','Remaining','Faculty','Room requirement'].map(label=><th className="px-3 py-2" key={label}>{label}</th>)}</tr></thead><tbody>{rows.map(row=><tr className="cursor-pointer border-t hover:bg-slate-50" key={row.course_offering_id} onClick={()=>setSelected(row)}><td className="px-3 py-2">{statusLabel(row.status)}</td><td className="px-3 py-2 font-medium">{row.course_code}</td><td className="px-3 py-2">{row.course_name}</td><td className="px-3 py-2">{row.section}</td><td className="px-3 py-2">{row.program} · {row.year}</td><td className="px-3 py-2">{row.required_periods}</td><td className="px-3 py-2">{row.scheduled_periods}</td><td className="px-3 py-2">{Math.max(row.required_periods-row.scheduled_periods,0)}</td><td className="px-3 py-2">{row.faculty.join(', ')||'No Faculty Assigned'}</td><td className="px-3 py-2">{row.required_room_type||'—'}</td></tr>)}</tbody></table>{!rows.length&&data.scope_has_offerings&&s.incomplete_offerings>0&&<p className="p-8 text-center text-sm text-slate-500">No incomplete offerings match this section.</p>}</CardContent></Card>
 {selected&&<div className="fixed inset-0 z-50 flex justify-end bg-black/40" onClick={()=>setSelected(null)}><aside className="h-full w-full max-w-xl overflow-y-auto bg-white p-6" onClick={event=>event.stopPropagation()}><button className="no-print float-right" onClick={()=>setSelected(null)}>Close</button><h2 className="text-xl font-semibold">{selected.course_code} · {selected.course_name}</h2><p className="mt-1 text-sm text-slate-500">{selected.section} · {selected.program} · Year {selected.year}</p><dl className="mt-6 grid grid-cols-2 gap-4 text-sm">{[['Semester',selected.semester],['Academic Session',selected.session],['Required Weekly Periods',selected.required_periods],['Scheduled Periods',selected.scheduled_periods],['Remaining Periods',Math.max(selected.required_periods-selected.scheduled_periods,0)],['Difference',selected.difference],['Status',statusLabel(selected.status)],['Activity Type',selected.activity_type_label],['Faculty',selected.faculty.join(', ')||'No Faculty Assigned'],['Required Room Type',selected.required_room_type||'—'],['Preferred Room',selected.preferred_room||'—'],['Actual Rooms Used',selected.actual_rooms.join(', ')||'—'],['Delivery Mode',selected.delivery_modes.join(', ')||'—']].map(([label,value])=><div key={String(label)}><dt className="text-slate-500">{label}</dt><dd className="mt-1 font-medium">{value}</dd></div>)}</dl></aside></div>}
 </div>;
}
