'use client';
import { useEffect, useMemo, useState } from 'react';
import { useParams } from 'next/navigation';
import { AdminLayout } from '@/components/layout/AdminLayout';
import { Header } from '@/components/layout/Header';
import { Card, CardContent } from '@/components/ui/card';
import { apiClient } from '@/lib/api/client';
type Row = Record<string, unknown>; type Option = { value: string; label: string };
const labels: Record<string,string> = {'faculty-workload':'Faculty Workload','room-utilization':'Room Utilization','section-timetable':'Section Timetable','faculty-timetable':'Faculty Timetable','room-timetable':'Room Timetable','course-allocation':'Course Allocation','unscheduled':'Unscheduled Classes','conflicts':'Conflict Report','free-rooms':'Free Rooms','version-activity':'Version Activity'};
const filterConfig: Record<string,{key:string;label:string;endpoint?:string;text?:boolean}[]> = {'faculty-workload':[{key:'faculty',label:'Faculty',endpoint:'/faculty/'},{key:'program',label:'Program',endpoint:'/programs/'},{key:'department',label:'Department',endpoint:'/departments/'},{key:'semester',label:'Semester',endpoint:'/semesters/'},{key:'session',label:'Academic session',endpoint:'/academic-sessions/'}],'room-utilization':[{key:'room',label:'Room',endpoint:'/rooms/'},{key:'semester',label:'Semester',endpoint:'/semesters/'},{key:'session',label:'Academic session',endpoint:'/academic-sessions/'}],'section-timetable':[{key:'section',label:'Section',endpoint:'/sections/'},{key:'program',label:'Program',endpoint:'/programs/'},{key:'semester',label:'Semester',endpoint:'/semesters/'},{key:'session',label:'Academic session',endpoint:'/academic-sessions/'}],'faculty-timetable':[{key:'faculty',label:'Faculty',endpoint:'/faculty/'},{key:'semester',label:'Semester',endpoint:'/semesters/'},{key:'session',label:'Academic session',endpoint:'/academic-sessions/'}],'room-timetable':[{key:'room',label:'Room',endpoint:'/rooms/'},{key:'semester',label:'Semester',endpoint:'/semesters/'},{key:'session',label:'Academic session',endpoint:'/academic-sessions/'}],'course-allocation':[{key:'course',label:'Course',endpoint:'/courses/'},{key:'program',label:'Program',endpoint:'/programs/'},{key:'department',label:'Department',endpoint:'/departments/'},{key:'semester',label:'Semester',endpoint:'/semesters/'},{key:'session',label:'Academic session',endpoint:'/academic-sessions/'}],'unscheduled':[{key:'section',label:'Section',endpoint:'/sections/'},{key:'program',label:'Program',endpoint:'/programs/'},{key:'semester',label:'Semester',endpoint:'/semesters/'}],'conflicts':[{key:'section',label:'Section',endpoint:'/sections/'},{key:'version',label:'Version',text:true}],'free-rooms':[{key:'weekday',label:'Weekday',text:true},{key:'time_slot',label:'Time slot',endpoint:'/time-slots/'},{key:'capacity',label:'Minimum capacity',text:true},{key:'room_type',label:'Room type',text:true}],'version-activity':[{key:'version',label:'Version',text:true}]};
const items = (data:unknown): Row[] => Array.isArray(data) ? data as Row[] : data && typeof data === 'object' ? ((data as Row).results ?? (data as Row).data ?? []) as Row[] : [];
const optionLabel = (item:Row) => String(item.name ?? item.label ?? item.code ?? item.title ?? item.number ?? item.id ?? '');
const scalar = (value:unknown) => value === null || value === undefined ? '' : typeof value === 'object' ? JSON.stringify(value) : String(value);
export default function Page() {
  const { report } = useParams<{report:string}>(); const config = filterConfig[report] ?? [];
  const [rows,setRows] = useState<Row[]>([]); const [options,setOptions] = useState<Record<string,Option[]>>({}); const [filters,setFilters] = useState<Record<string,string>>({}); const [sortKey,setSortKey] = useState(''); const [ascending,setAscending] = useState(true); const [loading,setLoading] = useState(true); const [error,setError] = useState(''); const [exporting,setExporting] = useState('');
  useEffect(() => { (filterConfig[report] ?? []).filter((item) => item.endpoint).forEach((item) => { apiClient.get(item.endpoint!).then(({data}) => setOptions((old) => ({...old,[item.key]:items(data).map((row) => ({value:String(row.id ?? row.uuid ?? row.value ?? ''),label:optionLabel(row)})).filter((option) => option.value)}))).catch(() => undefined); }); }, [report]);
  useEffect(() => { if (!report) return; const params = Object.fromEntries(Object.entries(filters).filter(([,value]) => value)); apiClient.get(`/reports/${report}/`,{params}).then(({data}) => {setRows(items(data));setLoading(false);}).catch(() => {setRows([]);setError('Unable to load this report.');setLoading(false);}); }, [report,filters]);
  const sortedRows = useMemo(() => [...rows].sort((a,b) => {if (!sortKey) return 0; const left=scalar(a[sortKey]),right=scalar(b[sortKey]),numeric=Number(left)-Number(right); const result=Number.isNaN(numeric)?left.localeCompare(right):numeric; return ascending?result:-result;}),[rows,sortKey,ascending]);
  const columns = sortedRows.length ? Object.keys(sortedRows[0]) : []; const update = (key:string,value:string) => setFilters((old) => ({...old,[key]:value}));
  const download = async (format:'csv'|'xlsx') => {setExporting(format);try{const response=await apiClient.get(`/reports/${report}/`,{params:{...filters,export:format},responseType:'blob'});const url=URL.createObjectURL(response.data);const anchor=document.createElement('a');anchor.href=url;anchor.download=`${report}-${new Date().toISOString().slice(0,10)}.${format}`;anchor.click();URL.revokeObjectURL(url);}catch{setError(`Unable to export this report as ${format.toUpperCase()}.`);}finally{setExporting('');}};
  const toggle = (column:string) => {if(sortKey===column)setAscending((value)=>!value);else{setSortKey(column);setAscending(true);}};
  return <AdminLayout><Header title={labels[report]??'Report'}/><main className="report-print-sheet mx-auto w-full max-w-[1500px] space-y-5 p-5 sm:p-8"><div className="no-print"><h1 className="text-2xl font-semibold">{labels[report]??'Report'}</h1><p className="mt-1 text-sm text-slate-500">Data derived from the current published timetable by default.</p></div><Card className="no-print"><CardContent className="flex flex-wrap items-end gap-3 p-4">{config.map((item)=>item.text?<label className="text-sm text-slate-600" key={item.key}>{item.label}<input className="mt-1 block rounded border px-3 py-2 text-sm" value={filters[item.key]??''} onChange={(event)=>update(item.key,event.target.value)} placeholder={`Filter by ${item.label.toLowerCase()}`}/></label>:<label className="text-sm text-slate-600" key={item.key}>{item.label}<select className="mt-1 block min-w-44 rounded border bg-white px-3 py-2 text-sm" value={filters[item.key]??''} onChange={(event)=>update(item.key,event.target.value)}><option value="">All</option>{(options[item.key]??[]).map((option)=><option value={option.value} key={option.value}>{option.label}</option>)}</select></label>)}<button className="rounded bg-slate-900 px-3 py-2 text-sm font-medium text-white" onClick={()=>window.print()}>Print / Save PDF</button><button className="rounded border px-3 py-2 text-sm" disabled={!!exporting} onClick={()=>download('csv')}>{exporting==='csv'?'Exporting…':'Export CSV'}</button><button className="rounded border px-3 py-2 text-sm" disabled={!!exporting} onClick={()=>download('xlsx')}>{exporting==='xlsx'?'Exporting…':'Export XLSX'}</button></CardContent></Card>{error&&<p className="no-print rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}{loading?<p>Loading report…</p>:!sortedRows.length?<Card><CardContent className="p-8 text-center text-slate-500">No report data is available for the selected filters.</CardContent></Card>:<Card><CardContent className="overflow-x-auto p-0"><table className="report-table w-full text-left text-sm"><thead className="bg-slate-50"><tr>{columns.map((column)=><th className="whitespace-nowrap px-4 py-3 font-semibold" key={column}><button className="text-left" onClick={()=>toggle(column)}>{column.replaceAll('_',' ')} {sortKey===column?(ascending?'↑':'↓'):''}</button></th>)}</tr></thead><tbody>{sortedRows.map((row,index)=><tr className="border-t" key={String(row.entry_id??row.id??index)}>{columns.map((column)=><td className="whitespace-nowrap px-4 py-3 align-top" key={column}>{scalar(row[column])}</td>)}</tr>)}</tbody></table></CardContent></Card>}</main></AdminLayout>;
}
