'use client';
import { useEffect, useMemo, useState } from 'react';
import { useParams } from 'next/navigation';
import { AdminLayout } from '@/components/layout/AdminLayout';
import { Header } from '@/components/layout/Header';
import { Card, CardContent } from '@/components/ui/card';
import { ReportAnalyticsSection } from '@/components/reports/ReportAnalyticsSection';
import { apiClient } from '@/lib/api/client';

type Row = Record<string, unknown>; type Option = { value: string; label: string }; type Filter = { key: string; label: string; endpoint?: string; text?: boolean; select?: 'weekday'|'projector' };
const labels: Record<string,string> = {'faculty-workload':'Faculty Workload','room-utilization':'Room Utilization','section-timetable':'Section Timetable','faculty-timetable':'Faculty Timetable','room-timetable':'Room Timetable','course-allocation':'Course Allocation','unscheduled':'Unscheduled Classes','conflicts':'Conflict Report','free-rooms':'Free Rooms','version-activity':'Version Activity'};
const simple = [{key:'semester',label:'Semester',endpoint:'/semesters/'},{key:'session',label:'Academic session',endpoint:'/academic-sessions/'}];
const faculty = [{key:'faculty',label:'Faculty',endpoint:'/faculty/'},{key:'program',label:'Program',endpoint:'/programs/'},{key:'department',label:'Department',endpoint:'/departments/'},{key:'semester',label:'Semester',endpoint:'/semesters/'},{key:'session',label:'Academic session',endpoint:'/academic-sessions/'}];
const filterConfig: Record<string,Filter[]> = {'faculty-workload':faculty,'room-utilization':[{key:'room',label:'Room',endpoint:'/rooms/'},...simple],'section-timetable':[{key:'section',label:'Section',endpoint:'/sections/'},{key:'program',label:'Program',endpoint:'/programs/'},...simple],'faculty-timetable':faculty,'room-timetable':[{key:'room',label:'Room',endpoint:'/rooms/'},...simple],'course-allocation':[{key:'course',label:'Course',endpoint:'/courses/'},{key:'program',label:'Program',endpoint:'/programs/'},{key:'department',label:'Department',endpoint:'/departments/'},...simple],'unscheduled':[{key:'section',label:'Section',endpoint:'/sections/'},{key:'program',label:'Program',endpoint:'/programs/'},{key:'semester',label:'Semester',endpoint:'/semesters/'}],'conflicts':[{key:'section',label:'Section',endpoint:'/sections/'},{key:'version',label:'Version',text:true}],'free-rooms':[{key:'weekday',label:'Weekday',select:'weekday'},{key:'time_slot',label:'Time slot',endpoint:'/time-slots/'},{key:'capacity',label:'Minimum capacity',text:true},{key:'room_type',label:'Room type',text:true},{key:'projector',label:'Projector',select:'projector'}],'version-activity':[{key:'version',label:'Version',text:true}]};
const weekdays=[['0','Monday'],['1','Tuesday'],['2','Wednesday'],['3','Thursday'],['4','Friday'],['5','Saturday'],['6','Sunday']]; const projectors=[['true','Available'],['false','Not Available']];
const items=(data:unknown):Row[]=>Array.isArray(data)?data as Row[]:data&&typeof data==='object'?((data as Row).results??(data as Row).data??[]) as Row[]:[]; const optionLabel=(row:Row)=>String(row.name??row.label??row.code??row.title??row.number??row.id??'');

export default function Page(){
 const {report}=useParams<{report:string}>(); const config=filterConfig[report]??[];
 const [rows,setRows]=useState<Row[]>([]),[options,setOptions]=useState<Record<string,Option[]>>({}),[filters,setFilters]=useState<Record<string,string>>({}),[sortKey,setSortKey]=useState(''),[ascending,setAscending]=useState(true),[loading,setLoading]=useState(true),[error,setError]=useState(''),[exporting,setExporting]=useState('');
 useEffect(()=>{let active=true; const requests=(filterConfig[report]??[]).filter(x=>x.endpoint).map(x=>apiClient.get(x.endpoint!).then(({data})=>({key:x.key,value:items(data).map(row=>({value:String(row.id??row.uuid??row.value??''),label:optionLabel(row)})).filter(option=>option.value)}))); Promise.all(requests).then(values=>{if(active)setOptions(old=>values.reduce((next,item)=>({...next,[item.key]:item.value}),{...old}))}).catch(()=>undefined); return()=>{active=false}},[report]);
 useEffect(()=>{if(!report)return;let active=true;const controller=new AbortController();const params=Object.fromEntries(Object.entries(filters).filter(([,value])=>value));const timer=window.setTimeout(()=>{if(active)setLoading(true)},0);apiClient.get(`/reports/${report}/`,{params,signal:controller.signal}).then(({data})=>{if(active){setRows(items(data));setError('')}}).catch((cause:unknown)=>{if(active&&!controller.signal.aborted){setRows([]);setError('Unable to load this report.')}}).finally(()=>{if(active){window.clearTimeout(timer);setLoading(false)}});return()=>{active=false;controller.abort();window.clearTimeout(timer)}},[report,filters]);
 const sorted=useMemo(()=>[...rows].sort((a,b)=>{if(!sortKey)return 0;const left=String(a[sortKey]??''),right=String(b[sortKey]??'');return ascending?left.localeCompare(right):right.localeCompare(left)}),[rows,sortKey,ascending]); const columns=sorted.length?Object.keys(sorted[0]):[]; const update=(key:string,value:string)=>setFilters(old=>({...old,[key]:value}));
 const download=async(format:'csv'|'xlsx')=>{setExporting(format);try{const response=await apiClient.get(`/reports/${report}/`,{params:{...filters,export:format},responseType:'blob'});const url=URL.createObjectURL(response.data);const anchor=document.createElement('a');anchor.href=url;anchor.download=`${report}.${format}`;anchor.click();URL.revokeObjectURL(url)}catch{setError(`Unable to export this report as ${format.toUpperCase()}.`)}finally{setExporting('')}};
 return <AdminLayout><Header title={labels[report]??'Report'}/><main className="report-print-sheet mx-auto w-full max-w-[1500px] space-y-5 p-5 sm:p-8"><div className="no-print"><h1 className="text-2xl font-semibold">{labels[report]??'Report'}</h1><p className="mt-1 text-sm text-slate-500">Data derived from the current published timetable by default.</p></div><Card className="no-print"><CardContent className="flex flex-wrap items-end gap-3 p-4">{config.map(item=><label className="text-sm text-slate-600" key={item.key}>{item.label}{item.select?<select className="mt-1 block min-w-44 rounded border bg-white px-3 py-2 text-sm" value={filters[item.key]??''} onChange={event=>update(item.key,event.target.value)}><option value="">{item.select==='weekday'?'All weekdays':'All'}</option>{(item.select==='weekday'?weekdays:projectors).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select>:item.text?<input className="mt-1 block rounded border px-3 py-2 text-sm" value={filters[item.key]??''} onChange={event=>update(item.key,event.target.value)} placeholder={`Filter by ${item.label.toLowerCase()}`}/>:<select className="mt-1 block min-w-44 rounded border bg-white px-3 py-2 text-sm" value={filters[item.key]??''} onChange={event=>update(item.key,event.target.value)}><option value="">All</option>{(options[item.key]??[]).map(option=><option value={option.value} key={option.value}>{option.label}</option>)}</select>}</label>)}<button className="rounded bg-slate-900 px-3 py-2 text-sm text-white" onClick={()=>window.print()}>Print / Save PDF</button><button className="rounded border px-3 py-2 text-sm" disabled={!!exporting} onClick={()=>download('csv')}>Export CSV</button><button className="rounded border px-3 py-2 text-sm" disabled={!!exporting} onClick={()=>download('xlsx')}>Export XLSX</button></CardContent></Card>{error&&<p className="no-print rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}{loading?<p>Loading report...</p>:<><ReportAnalyticsSection report={report} rows={sorted}/>{!sorted.length?<Card><CardContent className="p-8 text-center text-slate-500">No report data is available for the selected filters.</CardContent></Card>:<Card><CardContent className="overflow-x-auto p-0"><table className="report-table w-full text-left text-sm"><thead className="bg-slate-50"><tr>{columns.map(column=><th className="whitespace-nowrap px-4 py-3 font-semibold" key={column}><button onClick={()=>sortKey===column?setAscending(value=>!value):(setSortKey(column),setAscending(true))}>{column.replaceAll('_',' ')} {sortKey===column?(ascending?'↑':'↓'):''}</button></th>)}</tr></thead><tbody>{sorted.map((row,index)=><tr className="border-t" key={String(row.entry_id??row.id??index)}>{columns.map(column=><td className="whitespace-nowrap px-4 py-3 align-top" key={column}>{row[column]==null?'':typeof row[column]==='object'?JSON.stringify(row[column]):String(row[column])}</td>)}</tr>)}</tbody></table></CardContent></Card>}</>}</main></AdminLayout>;
}
