# Generated by Django 6.1.1 on 2026-09-20 23:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('common', '0001_initial'),
        ('faculty', '0001_initial'),
        ('institutions', '0001_initial'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='academics.academicsession')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_timetables', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='institutions.department')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='institutions.institution')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='academics.semester')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_no', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('SUPERSEDED', 'Superseded')], default='DRAFT', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_timetable_versions', to=settings.AUTH_USER_MODEL)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clones', to='scheduling.timetableversion')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_timetable_versions', to=settings.AUTH_USER_MODEL)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='scheduling.timetable')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday')])),
                ('block_length', models.PositiveIntegerField(default=1)),
                ('entry_type', models.CharField(choices=[('LECTURE', 'Lecture'), ('TUTORIAL', 'Tutorial'), ('PRACTICAL', 'Practical'), ('COMMON', 'Common'), ('LIBRARY', 'Library'), ('OTHER', 'Other')], default='LECTURE', max_length=20)),
                ('locked', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_entries', to='academics.courseoffering')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_entries', to='rooms.room')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_entries', to='academics.section')),
                ('start_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_entries', to='common.timeslot')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='scheduling.timetableversion')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleEntryFaculty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('PRIMARY', 'Primary'), ('CO_FACULTY', 'Co Faculty'), ('ASSISTANT', 'Assistant')], default='PRIMARY', max_length=20)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_assignments', to='faculty.faculty')),
                ('schedule_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_assignments', to='scheduling.scheduleentry')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('schedule_entry', 'faculty'), name='unique_entry_faculty')],
            },
        ),
        migrations.AddConstraint(
            model_name='timetableversion',
            constraint=models.UniqueConstraint(fields=('timetable', 'version_no'), name='unique_timetable_version'),
        ),
    ]
