export type Role = 'SUPER_ADMIN'|'ACADEMIC_ADMIN'|'TIMETABLE_COORDINATOR'|'HOD_OR_DEAN_APPROVER'|'CLASS_COORDINATOR'|'FACULTY'|'ROOM_LAB_COORDINATOR'|'READ_ONLY_VIEWER';
const write = new Set<Role>(['SUPER_ADMIN','ACADEMIC_ADMIN','TIMETABLE_COORDINATOR']);
export const canCreate = (role?: Role) => !!role && write.has(role);
export const canEdit = canCreate;
export const canDeactivate = canCreate;
export const canManageRooms = (role?: Role) => role === 'SUPER_ADMIN' || role === 'ROOM_LAB_COORDINATOR';
export const canManageFaculty = (role?: Role) => canCreate(role);
export const canImport = (role?: Role) => canCreate(role) || role === 'ROOM_LAB_COORDINATOR';
export const canEditAvailability = (role?: Role) => !!role && role !== 'READ_ONLY_VIEWER' && role !== 'HOD_OR_DEAN_APPROVER';
export const canManageFacultyAvailability = (role?: Role) => !!role && ['SUPER_ADMIN','ACADEMIC_ADMIN','TIMETABLE_COORDINATOR','ROOM_LAB_COORDINATOR'].includes(role);
export const canManageRoomAvailability = canManageRooms;
export const canCreateTimetable = canCreate;
export const canGenerateTimetable = canCreate;
export const canApplyGeneratedTimetable = canCreate;
export const canViewGenerationRuns = (role?: Role) => !!role;
export const canReviewTimetables = (role?: Role) => !!role && ['SUPER_ADMIN','ACADEMIC_ADMIN','HOD_OR_DEAN_APPROVER'].includes(role);
export const canEditSchedule = canCreate;
export const canDeleteScheduleEntry = canCreate;
export const canLockScheduleEntry = canCreate;
export const canValidateTimetable = (role?: Role) => !!role;
export const canViewFacultyTimetable = (role?: Role) => !!role;
export const canViewRoomAllocation = (role?: Role) => !!role;
export const canUseFreeRoomFinder = (role?: Role) => !!role;
